### ISSUE TITLE
[ui5-tooling-modules] fiori-tools-proxy with directLoad: true

### ISSUE THREAD

**Issue by mcannesson** [ui5-community/ui5-ecosystem-showcase#1007]
Hello,
I'm was trying to unsuccessfully use ui5-tooling-modules since I've found why it's not working, "directLoad: true" instruction in fiori-tools-proxy middleware cause import doesn't work.

It's not an issue, just to help anyone else with my older configuration to get this work.

Thank you.

Best regards.

**Comment by petermuessig** [comment]
Hi @mcannesson 

good hint, thanks for sharing - I'll clarify this with the fiori-tools-proxy guys. (@tobiasqueck - something to discuss for us).

BR,
Peter

**Comment by tobiasqueck** [comment]
@petermuessig if you set `directLoad: true` then the `@sap/ux-ui5-tooling` doesn't proxy requests to UI5 sources but intercepts html files and replaces paths like `/resources/sap-ui-core.js` with a full domain e.g. `https://ui5.sap.com/1.120.0/resources/sap-ui-core.js`.

Maybe the requests to your local module are redirected that way as well?
