### ISSUE TITLE
[cds-plugin-ui5] - pollutes the output of cds compile with error msg "...version is too old.." in BAS

### ISSUE THREAD

**Issue by 6of5** [ui5-community/ui5-ecosystem-showcase#1015]
Hi Peter,

if running in the BAS terminal for example `cds compile srv` in my cap project, I get for all output this extra line that cds-dk is too old, which is wrong as I use latest cds and cds-dk packages. 

```shell
[36m[cds-plugin-ui5][0m [32m[info][0m The cds build task requires @sap/cds-dk version >= 7.6.0! Skipping execution as your @sap/cds-dk version is too old...
{
  "definitions": {
```

my package.json is looks like:
```json
{
  "name": "cap-demo",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^7.9.2",
    "express": "^4"
  },
  "devDependencies": {
    "@cap-js/sqlite": "^1.7.1",
    "@sap/cds-dk": "^7.9.2",
    "@sap/eslint-plugin-cds": "^3.0.3",
    "cds-plugin-ui5": "^0.9.2",
    "eslint": "^9.3.0"
  },
  "scripts": {
    "start": "cds-serve",
    "watch-bookshop-ui5": "cds watch --open bookshop-ui5/index.html?sap-ui-xx-viewCache=false --livereload false"
  },
  "workspaces": [
    "app/*"
  ]
}
```
this is annoying as i store the various outputs of cds compile to track changes. 

Thx in advance for improving line 197, BR HP

**Comment by petermuessig** [comment]
The plugin will silently skip the execution if the version doesn't match.

Need to sync with @chgeo in general about this - best would be a proper way to get the current cds-dk version...

**Comment by petermuessig** [comment]
Release of version `0.9.3` is in progress...

**Comment by petermuessig** [comment]
After discussion with @chgeo we decided to not log an issue in the case as we just use feature detection. It is a bit strange why in you case the feature detection wasn't successful...
