### ISSUE TITLE
SAP HANA PROJECTS deploy button broken

### ISSUE THREAD

**Issue by dustinself** [ui5-community/ui5-ecosystem-showcase#1025]
**Describe the bug**
Using cds-plugin-ui5 seems to change the default behavior of BAS when the deploy (rocket-ship) icon is clicked in BAS under section SAP HANA PROJECTS. I get the error:
Executing task: echo 'Could not prepare environment: Error executing command "cds build --for hana". Reason: error occurred while executing command: "cds build"
[cds] - WARNING: The @sap/cds plugin /home/user/projects/btp-sandbox/packages/cap-server/node_modules/cds-plugin-ui5/cds-plugin.js contains an 'activate' function, which is deprecated and won't be supported in future releases. Please rewrite the plugin to return a Promise within 'module.exports'.

**To Reproduce**
1. Create a project that is configured to deploy hdi to hana cloud in "hybrid" scenario (that also utilizes cds-plugin-ui5)
2. Deploy using BAS rocket-ship icon

**Expected behavior**
Database objects should be deployed.

**Versions**
 - Browser: Chrome 126.0.6478.116

**Additional context**
I can work around this by running a cds build at the cap-server directory...and then run hdi deploy at the db directory.

**Comment by petermuessig** [comment]
Hi @dustinself 

the `activate` function has been removed since quite a while already. Do you use the latest version of the `cds-plugin-ui5` which is `0.9.3`? 

https://www.npmjs.com/package/cds-plugin-ui5?activeTab=versions

BR,
Peter

**Comment by petermuessig** [comment]
Closing as I assume this fixed the issue.
