### ISSUE TITLE
different line endings in generated <controller>-dbg.controller.js files

### ISSUE THREAD

**Issue by Joker2015** [ui5-community/ui5-ecosystem-showcase#1035]
Hello everyone,

I'm generating a sapui5 project from Typescript sources. The command line

ui5 build --clean-dest --include-task=generateCachebusterInfo

creates a new "dist" directory with several target files per source. One of these files is the "debug controller" <controller>-dbg.controller.js (i.e. App-dbg.controller.js).

When uploading the created files to the ABAP repository using the ADT service, the service complains about different line endings in one file. A closer inspection found out that the generated file <controller>-dbg.controller.js  uses CRLF as line ending on every line except in the last two lines, where only LF is used.

I'm using    
- "ui5-tooling-transpile": "^3.4.5" in my package.json
> node -v
v20.15.1
> npm -v                                
10.8.2
on Windows 11.

I hope that that problem is really caused by this plugin, if this is not the case please point me to the correct package.
best regards - Joachim

**Comment by petermuessig** [comment]
Found it - good catch - I'll fix it

**Comment by petermuessig** [comment]
On Mac it would not have happened 😉

**Comment by Joker2015** [comment]
many thanks for your fast response
