### ISSUE TITLE
[ui5-tooling-modules] middleware/task/tooling failing on specVersion check if ui5.yaml file after version 4 release

### ISSUE THREAD

**Issue by eurushibata** [ui5-community/ui5-ecosystem-showcase#1054]
After ui-tooling version 4 was release not all modules were updated with its dependencies, causing the bellow error that cannot identify specVersion: "4.0" of ui5.yaml file.

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/f6370da8-a85b-4278-8f58-14f96269ef8e">

the example bellow is using ui5-middleware-ui5 but the latest version still imports: "@ui5/project": "^3.9.2"

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-ui5/package.json#L18

I haven't tested with other middlewares but same issue possibly will occur.

**Comment by petermuessig** [comment]
Hi @eurushibata - good catch - need to check tomorrow

**Comment by petermuessig** [comment]
@eurushibata with the fix from #1058 it should work now.

**Comment by eurushibata** [comment]
Thank you @petermuessig
