### ISSUE TITLE
[ui5-tooling-modules] - Local dependency

### ISSUE THREAD

**Issue by mcannesson** [ui5-community/ui5-ecosystem-showcase#1068]
**Describe the bug**
Hello,
I try to integrate a local dependency using file: in the package.json
![image](https://github.com/user-attachments/assets/ed2df682-8588-4f27-a7a8-f9c73bf023e7)
It seems ok with npm install I see it in node_modules but i can't start or build the application.

**To Reproduce**
1. Get a local dependency
2. Add it to package.json dependencies
3. Try to Build or Run the app

**Expected behavior**
I want the local dependency works as well as it'll in a npm repository.
I've try the app without this dependency and it works well.

**Screenshots**
The error:
![image](https://github.com/user-attachments/assets/3c27af37-1458-4cb8-8f8f-3e441481cfa4)
"Error: ENOENT: no such file or directory, open 'C:\VSCodeRepo\" The url after that appears wrong (truncated).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by petermuessig** [comment]
Hi @mcannesson 

does the `mydependency` contain a `package.json`? I did a quick check on my Mac but my Windows machine is not available for the next days so I can check it only locally. My first test in the repo in the `ui5-app` using a local `mypackage` exporting a function did work. But it is using the dependency with `"mypackage": "file:thirdparty/mypackage` and in that directory I put a `package.json` and an `index.js` so that I can load the dependency with `mypackage`. For me this works. I'll try some more options and let you know if I can reproduce it.

**Comment by petermuessig** [comment]
Ah yes, please show me how you import the dependency into your UI5 application. THX

**Comment by mcannesson** [comment]
Hello,
Sure i've done a little test app here https://github.com/mcannesson/Sapui5_ImportLib.
You can run the app with this:
![image](https://github.com/user-attachments/assets/a4082403-df01-4ffe-8d2a-ea5c3c67e0a0)
With "normal" dependency loading it's ok:
![image](https://github.com/user-attachments/assets/dedf183e-ceee-4dd7-b28d-f770f4520f0b)
![image](https://github.com/user-attachments/assets/9390009c-1160-439a-b280-c41768d6af15)
But if you change it by local dependency (after removing node_modules and npm i):
![image](https://github.com/user-attachments/assets/9870cb35-88bc-47bc-af95-f07b5d491b8a)
![image](https://github.com/user-attachments/assets/c96fea4d-cc04-4121-8236-cb40efd5edc4)
Debug is killed and app not fully loaded
![image](https://github.com/user-attachments/assets/9dbb21e9-7dd9-4914-88f2-25f5ca67ef37)

Thanks.

**Comment by petermuessig** [comment]
@mcannesson thanks for your example - I could verify that my fix works - I changed the lookup of the npm package root folder. My previous solution was a bit naive. Fix is on the way... THX

**Comment by mcannesson** [comment]
Thanks a lot !

**Comment by petermuessig** [comment]
Once the change is verified, I release it immediately

**Comment by petermuessig** [comment]
Release is in progress and should be available soon:

```
Changes:
 - ui5-tooling-modules: 3.10.1 => 3.10.2
```
