### ISSUE TITLE
General usage PWA

### ISSUE THREAD

**Issue by ciction** [ui5-community/ui5-ecosystem-showcase#1077]
### Discussed in https://github.com/ui5-community/ui5-ecosystem-showcase/discussions/1076

<div type='discussions-op-text'>

<sup>Originally posted by **ciction** September 13, 2024</sup>
Hi All,

I just generated the most basic UI5 application using the default template wizard in BAS.
Basic template, Empty datasource,..

I've followed the steps:
1) npm install ui5-task-pwa-enabler --save-dev
2) made a literal copy of the UI5.yaml config

Upon running the npm build, I see that indeed the index.html has been modified, and there is a "manifest.webmanifest" generated in the dist folder.

When running the default npm start however, there is no manifest detected when I checkt the "application" tab in the brower.

Am I missing something?
Are there any additional steps needed to make this work?

Kind regards,
Christophe Swolfs</div>

**Comment by petermuessig** [comment]
Hi @ciction 

what does the "npm start" call do? Is it using the UI5 tooling to run the application from the `dist` folder or from the source code? 

THX and BR,
Peter

**Comment by ciction** [comment]
Hi @petermuessig, 
Thanks for the quick reply,
I'm investigating my fist PWA setup and thought this tool might help a lot.

So the commands I'm using are just the default ones from the BAS Template wizard:

"start": "fiori run --open \"test/flpSandbox.html?sap-ui-xx-viewCache=false#project1-display\"",

I saw that the tool updates the index.html however, so I'm just manually going to the root folder and opening index.html once my app is running.


![image](https://github.com/user-attachments/assets/758013f8-acd3-47b2-9f55-5d6145a259ab)

Not sure if this is related, but I get the following message as well:
![image](https://github.com/user-attachments/assets/a20d4ce0-4563-44d1-b1f1-5bcdb20d5a8f)

**Comment by petermuessig** [comment]
Hi @ciction ,

the PWA is only used when running the application "standalone" not in the launch pad or the sandbox. The manifest is declared in the `index.html` of the application which isn't used when starting applications inside the launch pad as it loads the `manifest.json` and the `Component.js`. But the manifest which is loaded here is only for the UI5 runtime. The PWA manifest is declared in the `index.html` as `<LINK>` tag.

In case of UI5 applications converted to PWA, you must run them from the `index.html` out of the `dist` folder which contains the built assets. Only then the browser will load the web app manifest and the application is launched as PWA.

HTH and BR,
Peter

**Comment by ciction** [comment]
Hi @petermuessig,

My issue is now solved by applying your advice, but also by adding an additional parameter in the index.html file.

1) Running the app direclty from the dist folder
[ ui5-dist.yaml configuration
](https://github.com/SAP/ui5-tooling/issues/300#issuecomment-729637381)

2) Updating the webmanifest link, adding the "crossorigin" parameter
`<link rel="manifest" href="manifest.webmanifest">`
<br>to <br>
`<link rel="manifest" href="manifest.webmanifest" crossorigin="use-credentials">`

Thanks for your help,
Kr,
Christophe

**Comment by petermuessig** [comment]
Thx, @ciction to report back your solution - maybe we should consider to add the crossorigin attribute into the modification of the `index.html`. But overall, I'm happy to hear that your issue is solved. 👍
