### ISSUE TITLE
[ui5-tooling-modules-middleware] Exclude requests with regex

### ISSUE THREAD

**Issue by menof36go** [ui5-community/ui5-ecosystem-showcase#1082]
**Is your feature request related to a problem? Please describe.**
The middleware is really slow, because _getResource_ and _resolveModule_ are called for every request to /resources/.
In my case profiling and network monitor show that even simple requests to /resources/sap/... take more than 20x as long as without the middleware (~450ms per file compared to ~15ms per file without).

**Describe the solution you'd like**
Regex to skip middleware execution early, preferably right after the initial match for /resources/.
Similar to how _shouldSkipTransform_ is implemented currently, I would love to just provide a bunch of glob patterns that are excluded, something akin to:
```yaml
  excludes:
      - "sap/**"
      - "my/namespace/**"
```
I have tried this manually and had the desired result with immense speedup.

**Describe alternatives you've considered**

**Additional context**
I dont know if this has any side effects or if there is maybe some other option that can be configured already

**Comment by petermuessig** [comment]
Good idea! I try to also continuously improve the performance of the middleware since it is critical for development - but this seems to be an easy and pragmatic idea to exclude resources you know about. Maybe we can also define a kind of a default...

**Comment by petermuessig** [comment]
@menof36go I found a better solution, fix is coming with the PR #1085
