### ISSUE TITLE
Add cache handling 

### ISSUE THREAD

**Issue by BenReim** [ui5-community/ui5-ecosystem-showcase#168]
Thank you for this showcase project. It comes very handy. 👍 

This is an enhancement request. As resource caching is a central issue in todays web applications, it would be nice to add cache-handling to the best-practice-showcase project. Ideally, such a cache handling would take in to account more advance use-cases that are possible with the ui5-tooling, such as custom bundles.

**Comment by petermuessig** [comment]
I will try to think about this topic - I have recently played around with yet another cachebuster concept - Easter weekend is coming - maybe I find some time 😄

**Comment by BenReim** [comment]
Initially, I thought that having a custom task appending some hash to the build bundle (e.g.`sap-ui-custom.a294294.js`) could be a way. But then I realized that at times, files are not being loaded from the bundle (such in the case of `sap/ui/core/ComponentSupport.js`). 

Additionally, `css` / `json` files are currently not being bundled when running a a self-contained build, so that there are requests such `/resources/sap/m/themes/sap_fiori_3/library.css` and `/resources/sap/m/themes/sap_fiori_3/library-parameters.json` that need to be considered for a cache-handling mechanism as well.

**Comment by petermuessig** [comment]
Did you have a look into the `ui5-task-cachebuster` concept moving the resources into a timestamp folder and keeping the index.html on the root level? I think this should work out for the cache handling supporting all major concepts of UI5.

**Comment by BenReim** [comment]
Hi Peter, i checked the `ui5-task-cachebuster` - cool approach 👍 I too think this is a solution for most use case

I could image though that the option of self-contained bundles with unique file names could still come handy, e.g. thinking of more advanced service worker based caching strategies (offline-first use cases etc) - but perhaps that is more of ui5-tooling topic...

**Comment by petermuessig** [comment]
Regarding service workers and self-contained bundles, you may look into the `ui5-task-pwa-enabler`. Two students had the idea to PWAize a UI5 application with the help of a tooling extension. It has also options to select caching strategies. Maybe worth to re-invest into that topic at some point in time as also Safari get slightly better PWA support...

I'll close this issue for now... Thanks for all your inputs and thoughts... Appreciate it and if you have more, just let me know... 😄
