### ISSUE TITLE
Using http headers with cfdestination

### ISSUE THREAD

**Issue by resitamas** [ui5-community/ui5-ecosystem-showcase#231]
First of all, thank you for all these middlewares and tasks, they are really useful for us.

However, we would like to use the _**cfdestination**_ middleware, but unfortunately we cannot. The problem is that we are using a predefined JWT token during the development for our backend. Before we introduced UI5 tooling we created a custom approuter and we injected the token into the _Authorization_ header for every request. The relevant code for this:

```
var approuter = require('@sap/approuter');

var ar = approuter();

ar.beforeRequestHandler.use((req, res, next) => {
    req.headers['Authorization'] = <JWT_TOKEN>;
    next();
});
```

Is it possible to enhance the cfdestination middleware to make it possible to inject headers into the request?

Another idea that came to my mind is that leaving the cfdestination middleware as it is and enhancing the simpleproxy middleware with this header injection. That would mean we could control that the token is only used for certain destinations.

What do you think?

**Comment by vobu** [comment]
hi, whatever improves the day-to-day usage of `cfdestination` is fine with me! 
so go ahead and PR it :)
ps: there's been an ongoing discussion on a similar topic in another issue: https://github.com/petermuessig/ui5-ecosystem-showcase/issues/185

**Comment by Magoli1** [comment]
@vobu @resitamas 
To add some details here from the mentioned issue:
I thought a lot about how to enable the usage of the cfdestination middleware in conjunction with the approuter and XSUAA. In my eyes, when developing locally with XSUAA enabled services, the experience should be the same like when having the app deployed, to login and to be able to use the app, with the small but important difference that you are able to change files locally without the need to deploy them. This was also mentioned by others in the issue.

However, this use-case seems to differ from the one which I am working on and I really like your idea! 🚀 Maybe also a new option in the manifest which enables the usage of the token could fit?

BR Robert

**Comment by resitamas** [comment]
Hi @vobu, 
I've decided to go on with my second idea and improving the simpleproxy instead of the cfdestination. The PR for this: https://github.com/petermuessig/ui5-ecosystem-showcase/pull/250
