### ISSUE TITLE
Documentation / Usage of H2

### ISSUE THREAD

**Issue by timostark** [ui5-community/ui5-ecosystem-showcase#313]
Hi Peter,

I guess for most users it is clear - still maybe it should be added to the documentation that with Chrome 81 (SameSite Attribute - see https://www.chromium.org/updates/same-site ) the ui5-middleware-simpleproxy wont work correctly for Batch requests, for the same reason mentioned in #236 (csrf-token validation fails).
The solution is to simply use https using `ui5 serve --h2 `(SameSite=Lax - or just eliminate as today, is sufficient, no change on the proxy itself is required).
As most users will use the proxy for odata request forwarding - what do you think? Should it be added?

Thanks,
Timo

**Comment by petermuessig** [comment]
Hi @timostark ,

thanks for the feedback, good to communicate this behavior! If you want you can add this information to the `README.md` of the ui5-middleware-simpleproxy. Otherwise I can try to do this soon.

Thanks and best regards,
Peter

**Comment by Fjaoos** [comment]
Hi,
I tried the above mentioned method because the (some) $batch requests returned the message that the validation of the csrf token failed. 
When I add --h2 the cli asks me if I want to create a SSL certificate but fails because it cannot find openssl (windows 10 machine)

Is openssl a prequesite? What certificate needs to be created?

**Comment by petermuessig** [comment]
You can also use manually created certificates. The CLI allows to pass `key` and `cert` via CLI parameters:
https://sap.github.io/ui5-tooling/pages/CLI/

Or you just put them into `$HOME/.ui5/server/server.key` and `$HOME/.ui5/server/server.cert`.

The UI5 tooling is using the following NPM package to create the self-signed certificate:
https://www.npmjs.com/package/devcert-sanscache (see also the sslUtil.js link below)

The NPM package also describes what it does on its NPM page (creating root cert,.

@matz3 @RandomByte maybe one of you can shed some more light 

Related links:
* https://sap.github.io/ui5-tooling/pages/Server/#ssl-certificates
* https://github.com/SAP/ui5-server/blob/master/lib/sslUtil.js

**Comment by matz3** [comment]
@Fjaoos yes, `openssl` is a prerequisite (For Windows.
There should be a message `Unable to find openssl - make sure it is installed and available in your PATH` when you don't have it installed. Other than that, it should work out-of-the-box. No need to manually run openssl or create a certificate.
