### ISSUE TITLE
stringreplacer - prefix configurable

### ISSUE THREAD

**Issue by nbmedikonda** [ui5-community/ui5-ecosystem-showcase#339]
**ui5-task-stringreplacer**

its not an issue but looking for this new option.is it possible to make the prefix configurable from ui5.yaml file?

I tried the below command  from package.json but it will not take the dot.In general all the env variables normally will have underscore(NODE_ENV) or it should start with stringreplacer_

"build": "cross-env stringreplacer.ENV=dev  ui5 build -a --clean-dest",

**Comment by petermuessig** [comment]
Hi @nbmedikonda ,

thanks for opening the issue here to point that out. If you are interested in contributing to the ui5-ecosystem feel free to do so. You can create a PR and put it to @vobu, @TheVivekGowda or me for review.

Best regards,
Peter

**Comment by mjturner** [comment]
I'd like to second @nbmedikonda's request, perhaps even changing the default from `.` to `_` as separator. A dot is [not a valid character](https://superuser.com/questions/495991/how-do-i-set-an-environmental-variable-with-a-dot) in a shell environment variable and trying to set such variables dynamically does require jumping through hoops (eg, using `env`).

**Comment by petermuessig** [comment]
@mjturner - ACK, @TheVivekGowda - what do you think? It is your contribution - would you also be fine to adopt this? And then make it configurable as well?

**Comment by petermuessig** [comment]
@dominikfeininger included this feature in the rework of the `ui5-tooling-stringreplace` tooling extension. It merges the `ui5-task-stringreplacer` and `ui5-middleware-stringreplacer`. The new default of the environment name is `UI5_ENV` and can even be customized.
