### ISSUE TITLE
Extending ui5-middleware-livetranspile to support different file types (e.g. TS support)

### ISSUE THREAD

**Issue by texttechne** [ui5-community/ui5-ecosystem-showcase#359]
Hi,

I would like to propose a change to make this middleware more generic. Currently it is restricted to consume `.js` files and I do at least require the consumption of TS files. I think this is the last step to make the middleware a full-blown transpiler enabling all Babel features.

The change itself: Switch from static lookup ([`resource.byPath`](https://github.com/petermuessig/ui5-ecosystem-showcase/blob/master/packages/ui5-middleware-livetranspile/lib/livetranspile.js#L69)) to configurable globbing pattern `.{js,ts}`.

The configuration I would imagine in `ui5.yaml` along these lines: `pattern: ".{js,ts}"` (default = ".js")

Of course, there will be a performance penalty for the dynamic lookup. I'd assume it would be neglible. We could also switch between globbing and static lookup depending on the pattern: either ".js" / ".ts" or ".{js,ts}"...

Another question: do you prefer to define / import all Babel dependencies in the middleware? That's currently more or less the case. I don't see any real problem with this approach and it makes the DX more comfortable. However, it feels kind of wrong... But it would allow to put the essential and most useful Babel transforms into the middleware and enable it by features flag via `ui5.yaml`. So is this the way to go or do you would like to create a separate livetranspile-middleware?

I would put together the PR if you're fine with this feature and you outline the direction to take :-)

**Comment by vobu** [comment]
hi, all of your suggestion sound good and are fine-by-me™ 😆 
and definitely please work on the existing `livetranspile` middleware, don't add more animals to the zoo!
couple of remarks:
- configureable file extension with `js` default is fine, but honestly, what other than `.{js,ts}` is out there? 
  -> why not just hard-wire it to `js|ts`?
- the point about the babel dependencies i'm not really getting: do you mean the dependencies in `package.json` (à la https://github.com/petermuessig/ui5-ecosystem-showcase/blob/d4eddf7fc1b64f832da5059d3d414f8ae454f1c7/packages/ui5-middleware-livetranspile/package.json#L12) or more the default babel config option (à la https://github.com/petermuessig/ui5-ecosystem-showcase/blob/d4eddf7fc1b64f832da5059d3d414f8ae454f1c7/packages/ui5-middleware-livetranspile/lib/livetranspile.js#L41)?
best, v.

**Comment by htammen** [comment]
@vobu there are a lot of possible script languages one could use (https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS). So I think it's always good not to hard-wire the extensions.

**Comment by texttechne** [comment]
The feature request is to allow patterns instead of using the hardwired ".js" extension. For example, when supporting TypeScript, it makes sense to allow for JS **and** TS consumption (pattern: ".{js|ts}"), then users can opt in to TS support file by file. And as soon as patterns are supported, they can be made configurable => no hardwiring necessary

Regarding the dependency question: I realize now that it is out-of-scope for the given PR.

**Comment by petermuessig** [comment]
@texttechne @vobu - you are too fast for me. I'll try to follow up on this over the weekend. I will also check the PR. THX...

**Comment by texttechne** [comment]
@petermuessig @vobu yeah, that was probably too fast 😀 

One thing we should discuss and which is not implemented correctly: Handling of multiple files for the same pattern. For example: Pattern = ".{js|ts|elm}" matches Component.js, Component.ts and Component.elm
Since only one file can be consumed: which one?

Status Quo:
* In the middleware I chose to do the following:
  - prefer the JS file & leave the rest up to chance
  - warn if multiple files match the given pattern
* I definitely missed to implement anything for this use case in the transpile task. Shame on me 😏 

My current standpoint is:
1. Let's support the case that a JS file may live side-by-side to one other file type, eg. TS
    - strategy: we always prefer the JS file
    - I think this could help, when gradually converting to TS or when just trying things out
1.  In any other case of having matched multiple files, we should throw an error
    - practical issues: should we prefer a certain file type over another because of alpanumeric ordering?!
    - I can't think of any use case, where the user would intentionally want to have it this way

**Comment by petermuessig** [comment]
This is indeed a good point. A precedence could be derived from the pattern, let's say the order of the extensions is important, but this might not be that trivial to determine. First I thought, it might be better to have different plugins for different purposes like JS transpile, TS transpile, but it is all Babel. BTW: what does Babel do in those cases? Is there some configuration foreseen for that cases?

**Comment by texttechne** [comment]
Actually it's not Babel determining which order files get transpiled => the files are fed file-by-file to Babel. 
It is `DuplexCollection` or `AbstractReader` from UI5 which is responsible 😄 

So the question is: If I specify ".{js,ts,elm}" in which order will `AbstractReader` return the file resources? Is the order guaranteed?

On the other hand, less is more. Less features, less code, less maintenance, less bugs...
So the first question should be: Do we need to handle this case or would it suffice to throw an error if multiple files match the specified pattern?

**Comment by petermuessig** [comment]
As I am a fan of keep it simple, I like your last suggestion - it even doesn't make sense to have all 3 files here which would cause nevertheless a conflict... 👍

**Comment by petermuessig** [comment]
Damn, I missed to update this issue. The `ui5-tooling-transpile` has the configuration option `filePattern` which allow you to specify the file extensions:
https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/ui5-tooling-transpile

Example: https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-app-ts/ui5.yaml#L23
