### ISSUE TITLE
Undocumented: Babel Polyfill is required for ui5-task-transpile

### ISSUE THREAD

**Issue by Kritten** [ui5-community/ui5-ecosystem-showcase#424]
As stated in this [blog](https://blogs.sap.com/2019/08/28/ui5-tooling-custom-transpiler-babel-builder-extension-task/) the ui5-task-transpile requires the babel polyfill (or regenerator-runtime and core-js in more recent versions).
This is not stated in the documention/README of ui5-task-transpile but I think it should be or am I missing something?

**Comment by petermuessig** [comment]
Hi @Kritten ,

The `ui5-task-transpile` task is pretty primitive - we did not document any of the required polyfills yet. In general, it might be useful to understand which ES6+ language features will lead to custom code and which ES6+ language features can be used without extra code. Especially for OpenUI5/SAPUI5 we have already the ES6 polyfills included for most of the APIs and this could be documented here. If you want you can also suggest something for the `README.md` here? 😃  

Cheers and happy holidays,
Peter

**Comment by petermuessig** [comment]
As newer browsers support `async` `await` properly, no transpile might be needed anymore. The alternative to transpile `async` is to convert them into ES6 `Promise`s using the following Babel plugin:

https://www.npmjs.com/package/babel-plugin-transform-async-to-promises

I will add a note to the documentation which closes this issue here...

**Comment by petermuessig** [comment]
Ah, damn - now I fully remember - the option `transpileAsync` of `ui5-tooling-modules` is exactly doing this. Here an example - how to set this flag:

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-app-ts/ui5.yaml#L25
