### ISSUE TITLE
Livetranspile: how to use file based Babel config

### ISSUE THREAD

**Issue by Shingaz** [ui5-community/ui5-ecosystem-showcase#454]
Is there something special to do to use the default Babel config at the root of the project?

It doesn't work for me as the `filename` given in the Babel options does not contains the full path, hence the root Babel config (`.babelrc.js` or `babel.config.json`) is not taken in account:
```
config.debug ? log.info(`...${pathname} transpiled!`) : null
const babelConfigForFile = merge({}, babelConfig, {
    filename: pathname // necessary for source map <-> source assoc
})
return babel.transformAsync(source, babelConfigForFile)
```

Also, how can we pass an empty Babel config in the middleware to configure it with a `.babelrc.js` only?

**Comment by lennart-m** [comment]
Hi, sorry for the late reply. Is this related to your comment [here](https://github.com/ui5-community/ui5-ecosystem-showcase/issues/246#issuecomment-760299437)?
I don't really understand what the issue is... can you maybe give an example?

**Comment by petermuessig** [comment]
The `ui5-tooling-transpile` with version `0.3.5` also support to read the configuration from the `.babelrc` files (or the alternatives) as known from Babel itself. If no inline configuration is present, it looks up for Babel config files, and if no config file is present, the default config is being used.
