### ISSUE TITLE
ui5-middleware-simpleproxy Enhancement

### ISSUE THREAD

**Issue by timostark** [ui5-community/ui5-ecosystem-showcase#517]
Hi All,

Quick question regarding "ui5-middleware-simpleproxy".
My Situation:
- Multiple custom UI5 libraries hosted on central server (using static web hosting - no npm consumption)
- UI5 apps are running in launchpad
- Middleware-Simpleproxy is used to access the ui5 libraries hosted on the server

Problems:
- Files of custom libraries are loaded using ".js" instead of "-dbg.js", giving a hard time to debug the libs locally
- Files of custom libraries are cached by the browser (even after reupload and cache buster invalidations)

I have solved that issue by adding a new parameter "debugSources" to the simpleproxy, which is rewriting ".js" to "-dbg.js" and a new paramter "cacheClear" which sets the cache control header accordingly to avoid caching the resources. 
I guess a more "common" solution would be to add a new parameter "rewriteRule" to rewrite URL paths according to RegEx patterns.

Question: Is that an overly specific problem for a custom library, or should I do a PR for that?

Regards,
Timo

**Comment by vobu** [comment]
can you hear that UI5 mob chanting "PR PR PR"!? yeah, me too 😁

**Comment by petermuessig** [comment]
Another alternative is to use UI5's debug URL parameter. You an always set the following URL parameter to load the debug sources for a specific namespaces, e.g.:

[https://sdk.openui5.org/?sap-ui-debug=sap/m,sap/ui/table](https://sdk.openui5.org/?sap-ui-debug=sap/m,sap/ui/table)

![image](https://user-images.githubusercontent.com/1589419/217587953-46c621fe-eb48-4ed9-8b57-a16a534fa7fa.png)
