### ISSUE TITLE
[ui5-middleware-cfdestination] Request to approuter when accessing index.html

### ISSUE THREAD

**Issue by stefania-santimbrean** [ui5-community/ui5-ecosystem-showcase#518]
Hello,

Firstly thank you so much for the tooling and middleware. I'm excited to develop UI5 using VSCode!

I'm trying to make a local setup for developing a UI5 app in VSCode which is served with approuter and is part of a Multi-target CAP application deployed on Cloud Foundry. The trick is that I need the authentication with XSUAA.

Is there any way when I access http://localhost:8080/index.html to be routed to approuter for XSUAA login first?

I'm going to explain a bit further what I mean.

My project structure:
```
|-- mta_project
    |-- ui_module
    |    |-- node_modules
    |    |-- webapp
    |    |   |-- index.html
    |    |   |-- manifest.json
    |    |    `-- ...
    |    |-- default-env.json
    |    |-- default-services.json
    |    |-- package.json
    |    |-- ui5.yaml
    |    |-- xs-app.json
    |    `-- ...
    |-- xs-security.json
    `-- ..
```

My `ui5.yaml` file:
```
specVersion: "2.3"
metadata:
  name: ui_module
type: application
server:
  customMiddleware:
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        authenticationMethod: route
        debug: true
        port: 1234
        xsappJson: xs-app.json
        destinations:
          - name: js_be
            url: http://localhost:3000
            forwardAuthToken: true
          - name: cds_be
            url: http://localhost:4004
            forwardAuthToken: true
```

My `xs-app.json` file:
```
{
	"welcomeFile": "/ui/index.html",
	"authenticationMethod": "route",
	"logout": {
		"logoutEndpoint": "/logout",
		"logoutPage": "/ui/index.html"
	},
	"routes": [
		{
			"source": "^/ui/(.*)$",
			"target": "$1",
			"csrfProtection": false,
			"localDir": "webapp",
			"cacheControl": "no-store",
			"authenticationType": "none"
		},
		{
			"source": "/node/(.*)",
			"target": "/$1",
			"destination": "js_be",
			"csrfProtection": false,
			"authenticationType": "xsuaa"
		},
		{
			"source": "/odata/(.*)",
			"target": "/$1",
			"destination": "cds_be",
			"csrfProtection": false,
			"authenticationType": "xsuaa"
		}
	]
}
```
In default-env and default-services I have the environment variables of the approuter deployed in CF.

And when I do `ui5 serve`:
- if I access directly http://localhost:8080/index.html -> all the calls to the 2 backends will fail (cause I'm not routed first to XSUAA login page to authenticate).
- if I first access for example http://localhost:8080/odata/ -> I'm routed to XSUAA login page, I authenticate and then if I access http://localhost:8080/index.html the backend calls will succeed.

So what I would need is when the regular local webserver is started and when I access index.html to make a request to the approuter. From the docs I have not found a possibility and I'm wondering if it's possible or can be possible?

I look forward to your thoughts on this question!

Thank you,
Stefania

**Comment by vobu** [comment]
hi, absolutely valid use-case! by chance, hacked that into existence recently together with Ronnie Sletta (Twitter: @rsletta) - try contacting him, i'm sure he'll share stuff :)
would be excellent if you could post an MVP/code sample for that here in this thread for other to reference!

**Comment by rsletta** [comment]
I have created a clean repository over at https://github.com/rsletta/ui5-vscode-local, that includes the tweaks as I recall them. There are some issues atm preventing it from running correctly, that I'm currently working on, but the configuration is basically identical to the working repository.

**Comment by stefania-santimbrean** [comment]
@rsletta thank you so much!

From what I see in the repo I assume that from `xs-app.json` this route should be what I'm looking for:
```
{
   "source": "^/index1.html",
   "target": "index1.html",
   "localDir": "uimodule/",
   "cacheControl": "no-cache, no-store, must-revalidate"
}
```

I tried to adapt to my folder structure:
```
{
	"source": "^/index.html",
	"target": "/index.html",
	"localDir": "webapp",
	"cacheControl": "no-cache, no-store, must-revalidate",
	"authenticationType": "xsuaa"
},
```

But it's not working :(  @vobu do you have any idea what might be missing?

Thanks so much!

**Comment by vobu** [comment]
hi @stefania-santimbrean - it's on my agenda for friday. should be something as a `cf-middleware` example anyway. so once i get it working, i'll morph it into the docs of bespoken middleware.

**Comment by stefania-santimbrean** [comment]
hello @vobu ,

Thanks so much! Highly appreciate the middlewares and the tooling 💯  They are an amazing improvement and help developing faster UI5.

Do you have an idea If it's possible to use this setup or make it work when the deployed approuter is used for multitenancy? I asked a different question for this: #519 as it's somehow a separate topic.

Thanks again,
Stefania

**Comment by vobu** [comment]
> Do you have an idea If it's possible to use this setup or make it work when the deployed approuter is used for multitenancy? I asked a different question for this: #519 as it's somehow a separate topic.

i do have that on the radar and will also check while i dig into the cf middleware

**Comment by vobu** [comment]
so i got it working, and the solution is 3-fold:
1. you need a `default-env.json` in `/` for the app router to pick up a default IdP.
it's easy to create one via `cf default-env $yourapp`
2. add authenticationType to the `index1.html`
```diff
diff --git a/xs-app.json b/xs-app.json
index 7b160cd..cb4e071 100644
--- a/xs-app.json
+++ b/xs-app.json
@@ -13,7 +13,8 @@
                        "source": "^/index1.html",
                        "target": "index1.html",
                        "localDir": "uimodule/",
-                       "cacheControl": "no-cache, no-store, must-revalidate"
+                       "cacheControl": "no-cache, no-store, must-revalidate",
+                       "authenticationType": "xsuaa"
                }
        ]
 }
```
3. and most important, but also most meeeeeh at the same time: `cf-middleware-destination`'s use of the app router doesn't allow for `localDir` setting in `xs-app.json`:
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/f4a7f1846f028b3ca3cc764dadb4a4518526fa4d/packages/ui5-middleware-cfdestination/lib/cfdestination.js#L33
but the `index1.html`-hack requires this to work.
so the only solution currently is to hack this out in `node_modules`:
```js
 // .filter((route) => !route.localDir && (options.configuration.allowServices || !route.service)); //ignore routes that point to web apps as they are already hosted by the ui5 tooling
 .filter((route) => (options.configuration.allowServices || !route.service)); //ignore routes that point to web apps as they are already hosted by the ui5 tooling
```
meh meh meh. triple meh.
-> I'll refactor the middleware to allow usage of `localDir` at config time, setting it to `false` per default.

**Comment by rsletta** [comment]
Great work tracking it down @vobu. I´ll make sure the readme of the repo reflects your findings. 👍

**Comment by stefania-santimbrean** [comment]
@vobu thanks so much for your support with this! Should I also close the issue or wait for the refactor of middleware first?

**Comment by vobu** [comment]
leave this open, please. I'll batch-close issues with the respective middleware commit

**Comment by stefania-santimbrean** [comment]
Hi @vobu ,

Thanksssss so much for this fix!!! I'm trying it out right now and was wondering about a small detail. So I want to allow localDir only for index.html so that I login, then switch to the UI5 files served by UI5 Tooling.

And how this happens now is that I go to http://localhost:8080/index.html, I'm routed to XSUAA login, then I'm routed to http://localhost:5000/index.html (which is not going to work, cause all the other UI5 files are on 8080) and I have to change the URL back to http://localhost:8080/index.html.

The best way would be if from the XSUAA login I can be routed back to http://localhost:8080/index.html. But this would mean the approuter to route back to the UI5 Tooling server. Do you think this is configurable somehow? I'm thinking about the possibility of extending the approuter after it is required in the cfdestination lib, but this seems a bit circular in my mind.

Kind regards,
Stefania
