### ISSUE TITLE
[ui5-middleware-cfdestination] with multitenant approuter possible?

### ISSUE THREAD

**Issue by stefania-santimbrean** [ui5-community/ui5-ecosystem-showcase#519]
Hello,

I am wandering if the `ui5-middleware-cfdestination` is usable in a scenario where the deployed approuter is in multitenant mode?

The only way I found possible to run the multitenant approuter locally was by extending it.
I have `server.js` with the following contents:
```
var approuter = require("@sap/approuter");

var ar = approuter();

ar.first.use(function myMiddleware(req, res, next) {
    req.headers["x-custom-host"] = process.env.mockHost;  
    console.error('x-custom-host request header overwritten with:' + process.env.mockHost);
    next();
});
ar.start();
```
And start it in the Terminal with: `node server.js`.

Is it possible to do this also when using the `ui5-middleware-cfdestination`?

Looking forward to your thoughts,
Best regards,
Stefania

**Comment by petermuessig** [comment]
@vobu , are you experienced with the multitenant capabilities of the approuter? I think this kind of feature here may be added to the cfdestination as well. The `custom-host` could be added also as a configuration option for the middleware and in case of present injected into the headers as `x-custom-host` right?

**Comment by vobu** [comment]
> @vobu , are you experienced with the multitenant capabilities of the approuter? I think this kind of feature here may be added to the cfdestination as well. The `custom-host` could be added also as a configuration option for the middleware and in case of present injected into the headers as `x-custom-host` right?

thx for the hin! will need some support/guidance on this. i'll get back to you on this once i have both the test setup and the new version for `cf-destination` in the pipeline.

**Comment by stefania-santimbrean** [comment]
@vobu I have an update about running the multitenant approuter on localhost.

There's no need to extend the approuter. I can just simply go to http://subdomain:localhost:5000. And in default-env.json I have: `TENANT_HOST_PATTERN: "^(.*).localhost"`.

This will extract the subdomain and know to call https://subdomain.authentication.eu10.hana.ondemand.com.

Do you think this can be included also in the cfdestination middleware somehow?

Please let me know if I can help in any way!

Kind regards,
Stefania

**Comment by vobu** [comment]
hi @stefania-santimbrean, thanks for the offer, any help/PR appreciated!
a possible coding approach could be:
- provide a config option to `cf-destination` à la `custom-host` (as @petermuessig suggested) that needs to (by convention) be identical to the `TENANT_HOST_PATTERN` in `default-env.json`
  see https://github.com/ui5-community/ui5-ecosystem-showcase/blob/ed6e6a9027e3a241016312aa968ce83760c16372/packages/ui5-middleware-cfdestination/lib/cfdestination.js#L17
- then use this setting at runtime and inject as `x-custom-host` into the approuter requests (https://www.npmjs.com/package/@sap/approuter#custom-headers)
  see https://github.com/ui5-community/ui5-ecosystem-showcase/blob/ed6e6a9027e3a241016312aa968ce83760c16372/packages/ui5-middleware-cfdestination/lib/cfdestination.js#L75
- write a test for that 😸 
  see https://github.com/ui5-community/ui5-ecosystem-showcase/pull/526/files#diff-fcd477e161dc15966d9b430e20eda94ab0ac3bfa2a6d3f8459c74550af2b2782R96

does that make sense for you?
best, v.
