### ISSUE TITLE
Double-Encoding-Issue

### ISSUE THREAD

**Issue by MaxDownman** [ui5-community/ui5-ecosystem-showcase#529]
Since Version 0.7.2 we have the issue that URIs get double encoded.

A simple example would be to add a OData-Service like this to your dataSources:
"oDataAnnotaions": {
				"uri": "/sap/opu/odata/IWFND/CATALOGSERVICE;v=2/Annotations(TechnicalName='%2FNAMESPACE%2FODATA_ANNO_MDL',Version='0001')/$value",
				"type": "ODataAnnotation"
			},

The root cause of it is that the string provided for the Annotation is already encoded with "%2F" as this would otherwise lead to issues with the URI as it is a "/".
In the deployed version on the Gateway it works perfectly fine like this.
With the UI5-Tooling however it double encodes "%2F" into "%252F".

This happens since version 0.7.2. [PR-516](https://github.com/ui5-community/ui5-ecosystem-showcase/pull/516).

It simply double encodes our URI.

If i try to use the unencoded URI in the manifest it also fails to work.

**Comment by vobu** [comment]
@sebbi08 - could you please have a look? thx!
