### ISSUE TITLE
[ui5-task-zipper] follow symlinks

### ISSUE THREAD

**Issue by MichaelFlucher** [ui5-community/ui5-ecosystem-showcase#535]
Hey, I'm using the `ui5-task-zipper` for the build task to package everything before creationg the .mta file. For reusability we have a Symbolic Link from multiple apps to one `i18n` folder which is included in every project, but the `ui5-task-zipper` simply ignores those files. 
Is it possible to support symbolic links?

**Comment by vobu** [comment]
assigning this to @IObert, the original author of the task.
but: what about adding this in a PR, @MichaelFlucher? :)
and: reaching far, but any chance you might also include a basic test setup similar to https://github.com/ui5-community/ui5-ecosystem-showcase/tree/master/packages/ui5-middleware-cfdestination/test? i'd help with that too

**Comment by MichaelFlucher** [comment]
Maybe I'll give it a try. So far I simply use following commands in Powershell to deep copy the whole webapp folder:
```powershell
rm -r -Force .\ProjectFolder\webapp-dist
Compress-Archive -Path .\ProjectFolder\webapp\* -DestinationPath .\ProjectFolder\webapp-dist.zip 
Expand-Archive -LiteralPath .\ProjectFolder\webapp-dist.zip -DestinationPath .\ProjectFolder\webapp-dist
rm .\ProjectFolder\webapp-dist.zip
```
Afterwards I change the ui5.yaml to use the webapp-dist folder instead of webapp

**Comment by MichaelFlucher** [comment]
After some debugging I noticed that the `ui5-task-zipper` doesn't even get the linked files. The UI5 Buildtool already omits them, so I created a Feature Request: https://github.com/SAP/ui5-tooling/issues/570
