### ISSUE TITLE
[ui5-task-stringreplacer] How to load either dev, staging or production .env?

### ISSUE THREAD

**Issue by piejanssens** [ui5-community/ui5-ecosystem-showcase#545]
Because it's the environment of the UI5 build tool that we need to configure with strings variables upon building (and not the environment where the UI5 is deployed), it makes sense that we can set the environment upon building through the scripts of package.json.  Is that possible somehow, given that `dotenv` is used?

```json
  "scripts": {
    "build:prod": "NODE_ENV=production ui5 build",
    "build:staging": "NODE_ENV=staging ui5 build",
  },
```

P.S. Same goes for ui5-middleware-stringreplacer

**Comment by petermuessig** [comment]
Hi @piejanssens ,

sorry, missed that issue here. 😟  This is indeed interesting - `custom-env` looks good IMO. Will you do a PR or should I check? It may take a bit for me...

BR, 
Peter

**Comment by petermuessig** [comment]
Fixed with https://github.com/ui5-community/ui5-ecosystem-showcase/pull/548
