### ISSUE TITLE
[ui5-task-zipper] Enhance includeDependencies flag to specify dependencies to include

### ISSUE THREAD

**Issue by HappyHepo** [ui5-community/ui5-ecosystem-showcase#550]
**Is your feature request related to a problem? Please describe.**
When I deploy a UI5 application to SAP BTP, I only need to include custom dependencies, but not the UI5 libraries.

**Describe the solution you'd like**
I would like to specify the dependency to include similar to how the builder specifies additional dependencies (possibly as another flag/flag value to only include the dependencies specified in the `ui5.yaml` under `builder` > `settings` > `includeDependency`)

**Describe alternatives you've considered**
Currently I use a custom npm script to zip the content of the dist folder, but I would like to configure the complete build in the `ui5.yaml`

**Comment by petermuessig** [comment]
Feature is available with `ui5-task-zipper` version `0.8.0`

**Comment by petermuessig** [comment]
Is the 'src-gen' folder present in the library?

**Comment by HappyHepo** [comment]
This works now with my setup
