### ISSUE TITLE
[ui5-middleware-cfdestination] Error Message: No UAA service found although default-env is available

### ISSUE THREAD

**Issue by Smux** [ui5-community/ui5-ecosystem-showcase#554]
I generated a new application with the easy-ui5-generator and wanted to locally connect my Fiori app with my backend running on Cloud Foundry. The backend is a NodeJs app which is XSUAA protected. 
To test my backend I have created an approuter and pushed this to my space as well. The approuter is bound to the same xsuaa instance as the backend. The deployed approuter works like a charm and I can authenticate easily and get data from my Nodejs backend.
However when I use the cfdestination middleware it just tells me there is no UAA found, although I have met the following requirements:

- Get default-env.json via default env plugin (in this case from my deployed approuter)
- The default-env.json contains the valid xsuaa credentials in the correct format. I compared the format also with your "test/auth" examples.
- Properly configure xs-app.json to route /backend to destination "backend"
- Configure the middleware so that "backend" leads to the URL of my protected Nodejs app
- Set authenticationMethod and authenticationType in xs-app.json and ui5.yaml
- I tried with and without "forwardAuthToken" property
- I tried putting the default-env.json on the root of my MTA project and also on the root of the UIModule, none of which worked

![image](https://user-images.githubusercontent.com/19520637/147574698-59062d2b-c548-471f-84b3-60dc124edf1f.png)
![image](https://user-images.githubusercontent.com/19520637/147574720-4cb70936-14a3-4e18-89be-35186909884d.png)
![image](https://user-images.githubusercontent.com/19520637/147574640-2a761eee-3965-4e25-8bb5-bfa3822f1dc6.png)

What am I doing wrong? is this a bug? Is a destination service binding also required?

MacOS 12.0.1
MS Edge Version 96.0.1054.53 (Official build) (x86_64)
Using latest version of ui5-middleware-cfdestinatino (0.8.0)

**Comment by Smux** [comment]
I just noticed I had the wrong URL in the destination config, it is now the backend and not the router url. However the issue is still the same because it already fails at "npm start"
"start": "ui5 serve --config=uimodule/ui5.yaml  --open index.html",

**Comment by vobu** [comment]
it sure smells like #547 with the ui5 tooling and the cf-destination-middleware not picking up `default-env.json` when there's a custom path to `xs-app.json` (see also #508). As a temporary workaround (until #547 gets in), try placing both `xs-app.json` and `default-env.json` in the same dir, e.g. `/`.

**Comment by Smux** [comment]
awesome it works!! thanks so much :)
