### ISSUE TITLE
[ui5-middleware-servestatic][ui5-middleware-simpleproxy] Usage as replacement of `framework`

### ISSUE THREAD

**Issue by treee111** [ui5-community/ui5-ecosystem-showcase#555]
**Describe the bug**
We develop custom apps which depend on our custom libraries. We moved to UI5Tooling some months ago and it works flawless for local development so far.

Our setup:
- separate repositories per app and library
- SAPUI5 framework v1.71.35  stored local on each Laptop and served using Middleware ui5-middleware-servestatic in all apps&libraries
- custom theme on our onpremise Gateway server and in the library repository as well
- external D3 library in use (not via shims, the file is stored in our Repo)
- karma-ui5 QUNIT tests working locally
- local launchpad for each app

So far, we are OK and far more in UI5-standard then with the grunt. But I want to go further, implement the newest features.
I want to (in order of importance):

1. make karma-ui5 tests to run in our CI/CD pipeline (UI5 framework can't be local anymore)
2. publish libraries to our company NPM and consume from there (actually we are doing this locally) 
3. Integrate external libraries via shims
4. centralise theming

I know that live would be easier if we were on SAPUI5 framework >= 1.76.0 but that willl take some time.

In the first run, I thought of changing from `ui5-middleware-servestatic` to `ui5-middleware-simpleproxy` to serve from the SAPUI5 framework from cloud (for points 1. and 2. above).
I tried a lot of things with our custom apps but wasn't successful.

To have a smaller example I forked from the UI5con2020 example and tried things there.
I made explanatory commits on branch `use-servestatic` - https://github.com/treee111/ui5con20-ui5-tooling/tree/use-servestatic.

I first switched from `framework` in the ui5.yaml to `ui5-middleware-servestatic` and wanted to further switch to `ui5-middleware-simpleproxy` for serving the SAPUI5 framework. I used SAPUI5 Version 1.79.2 in this example to be "equal" to openUI5 1.79.0 which was used initially.
The first switch wasn't as easy as I thought so I excluded the theme-library and later also the library from loading.

1. Is is possible to use the middlewares not only in the "running" application (here: `app`) but also in libraries (`library`, `theme-library`)? I thought they would do more or less the same then`framework` in the ui5.yaml but for all libraries (and not only ones named in ui5.yaml)
2. How should I use the middlewares in such a szenario?
3. Building the `theme-library` using `ui5-middleware-servestatic` does also not work. I tried with `ui5-task-copy-themes` but this task does not recognice the themes because no `framework` is given
4. In my opinion, the themes are making trouble here?! 
5. Any other advice? This is a very long post.. should I write that better in any other place (blogpost/SAP-Community...)

**To Reproduce**
1. Clone https://github.com/treee111/ui5con20-ui5-tooling
2. Switch to branch `use-servestatic`
3. Follow https://github.com/treee111/ui5con20-ui5-tooling/tree/use-servestatic/demo-project to get the app running

For reproducing with `ui5-middleware-servestatic`:
4. Download 1.79.2 from https://tools.hana.ondemand.com/#sapui5 and store local
5. Adjust app/ui5.yaml to the path of the downloaded SAPUI5 framework

5. Switch between the commits and read the commit messages
  5.1. After switching a branch do `yarn` and then start the app via `yarn start`

**Expected behavior**
I expect a possibility to make use of most of the UI5Tooling features with a lower SAPUI5 Version than 1.76.0.

**Screenshots**

Commit https://github.com/treee111/ui5con20-ui5-tooling/commit/e0c629e8c3cea9d49653b1a195fa8f22c6838801
![grafik](https://user-images.githubusercontent.com/53038537/147569121-322c981e-df09-4bf6-b2b5-357c0374f2bd.png)
![grafik](https://user-images.githubusercontent.com/53038537/147569171-081dae7f-a0e8-4a1f-af38-a379e87ecaea.png)

Commit https://github.com/treee111/ui5con20-ui5-tooling/commit/23b6f94371b2738f3fe53f18827709fdb206234a:
![grafik](https://user-images.githubusercontent.com/53038537/147578489-36464a92-7a79-4dc2-9a15-8e988d59b853.png)
![grafik](https://user-images.githubusercontent.com/53038537/147578498-d852d6c2-7e69-4962-812e-cb64ea3a9056.png)

**Desktop (please complete the following information):**
 - OS: macOS and Windows
 - Browser Chrome
 - Version 96

**Additional context**
Related to https://github.com/SAP/ui5-tooling/issues/265

**Comment by petermuessig** [comment]
Hi @treee111 , thanks for the issue - although the issue is pretty long and I need to spend some time on it to fully get it it is ok to have it here as an issue. Partially, this is related to how the tooling works and independent from the ecosystem, but we can sort this out here in the issue.

**Comment by petermuessig** [comment]
Oh man, this issue was open too long (SORRY!) without being recognized (and I assume you are in the meantime on newer versions). In the meantime many things have changed and interesting options to use other older versions for the UI5 tooling are the usage of the [(static) dependency definition](https://sap.github.io/ui5-tooling/v3/pages/Overview/#static-dependency-definition) (to provide UI5 tooling metadata for projects not having a `ui5.yaml`) or the [workspace concept](https://sap.github.io/ui5-tooling/v3/pages/Workspace/) which allows to consume local UI5 projects in a kind of a workspace for your application (for build and serve).

**Comment by treee111** [comment]
Hi @petermuessig don't worry. I missed on closing this issue. Since we upgraded to a SAP Gateway supporting 1.96 we are able to use standard UI5 libary via NPM.
I hadn't enoght time until now to check if it works for karma tests (what this issue is about). Thanks for your heads up and the two links - I need to dig into this again! :-)
