### ISSUE TITLE
ui5-middleware-cfdestination - connect to SAP system

### ISSUE THREAD

**Issue by Smux** [ui5-community/ui5-ecosystem-showcase#556]
Is there any way to configure the proxy to also be able to handle requests to an SAP on premise system? 
Currently I get the error message "unable to get local issuer certificate" which makes sense, but is there a way to proxy those requests successfully as well?

**Comment by vobu** [comment]
if you're trying to connect from your local env via `ui5-middleware-cfdestination` to BTP, then consume a destination "living" there, then back to a on-prem system: the answer is "no". BTP's connectivity service (underlying the destination service) is a reverse proxy that only allows connection from private, BTP-only networks.
Your 2 options are:
1. connect from your local setup directly to the on-prem system. A destination is "only" a mitigator anyway, enabling secure communication to the on-prem system at runtime. For dev time, I'd consider a connection from one local system to another local system not critical.
2. use https://github.com/jowavp/sap-cf-proxy - this utilizes `cf ssh` to tunnel from your local dev env via a BTP destination to an on-prem system.
hth, v.
