### ISSUE TITLE
[ui5-middleware-cfdestination] need websockets support

### ISSUE THREAD

**Issue by ddNils** [ui5-community/ui5-ecosystem-showcase#557]
We were trying to use a local websocket mock, which works fine, when it's directly used by the frontend. But we were unable to use this with ui5-middleware-cfdestination.

I did try to enable ws through the approuter xsappConfig like this:
```
    xsappConfig.websockets = {
        "enabled": true
    };
```
But I did have to add the additional ports to WS_ALLOWED_ORIGINS to get it working:
```
    process.env.WS_ALLOWED_ORIGINS = JSON.stringify([
        {
            "protocol": "http",
            "host": "localhost",
            "port": 8082
        }
    ]);
```
AND add express-ws to the internally used express server:
```
    expressWS = require('express-ws')(req.app);
```

This will forward the initial websocket UPGRADE request from the client to the mock server (on port 8082). Unfortunately it still does not work, as the line `req.pipe(request(url)).pipe(res)` only works for requests (not for continuous websockets). 

One possible solution could be to check the req method and use something else than a request to pipe (proxy) the request object to our mock api. This would still use approuter, but we would have to traverse destinations and add them to WS_ALLOWED_ORIGINS programmatically. And maybe other hacks.

An alternative could be to use a more uncomplicated router project like [http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware), I tried a quick experiment and it seems to work:
```
    // can be filled from destinations
    const proxyTable = {
        '/CRM_BACKEND_WS': 'http://localhost:8082', // path only
        '/CRM_BACKEND': 'http://localhost:8081' // path only
    };
  
    const proxyOptions = {
        target: 'http://localhost:8080',
        ws: true,
        router: proxyTable,
        logLevel: 'debug',
        proxyTimeout: 500
    };
    
    const myProxy = createProxyMiddleware(proxyOptions);

    return (req, res, next) => {    
        const app = req.app
        app.use(myProxy); // add the proxy to express

        next()
    }
```

**Comment by vobu** [comment]
hi @ddNils - I'm absolutely pro switching the deprecated `request` module for a solution that also supports websockets. @alperdedeoglu dropped me a line and wanted to tackle replacing `request` → let's put websocket support on the table for this as well!

**Comment by petermuessig** [comment]
Right now, the UI5 Tooling doesn't allow to enhance the express server with `express-ws`. We need to discuss this with @RandomByte and @matz3 - whether this could be enabled in future. Otherwise a workaround would be to put another express server around the UI5 Tooling and the AppRouter...
