### ISSUE TITLE
[ui5-tooling-modules]: consider the `browser` field in package.json when resolving dependencies 

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/ui5-ecosystem-showcase#602]
**Is your feature request related to a problem? Please describe.**

When trying to include third party code i.e. [marked.js](https://github.com/markedjs/marked) in your application it may happen that there are several builds available. In this particular case when trying to resolve the dependencies using Nodes native `require.resolve` only the `main` field is respected which leads to loading or rather trying to include a CommonJS module. See the [package.json](https://github.com/markedjs/marked/blob/801be0e93cec0b963ed724c48788800d154028a6/package.json#L7-L9). Trying to work with CommonJS leads to errors when parsing the code with espree [here](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/3077eff9c1261f959364ae2aacb1f85ed5bfdf2e/packages/ui5-tooling-modules/lib/task.js#L48). Ultimately even if it would work and you would bundle a `.cjs` module into your aplication, you'd end up with an error at run- or (at latest) buildtime as CommonJS simply does not work in a Browser.

This is not the only example. The usage of [UI Integration Cards](https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/index.html) also leads to errors at build time.

(extract from debugger: at Espree.pp$8.parseStatement (...\node_modules\acorn\dist\acorn.js:930:18))
```js
export default{_:{packageName:"@ui5/webcomponents-theming",fileName:"themes\\\\sap_fiori_3_dark\\\\parameters-bundle.css",content:':root{--sapBrandColor:#91c8f6;--sapHighlightColor:#91c8f6;--sapBaseColor:#29313a;--sapShellColor:#354a5f;--sapBackgroundColor:#1c2228;--sapFontFamily:"72","72full",Arial,Helvetica,sans-serif;--sapFontLightFamily:"72-Light","72-Lightfull","72","72full",Arial,Helvetica,sans-serif;--sapFontBoldFamily:"72-Bold","72-Boldfull","72","72full",Arial,Helvetica,sans-serif;--sapFon…tical:#de890d;--sapChart_Good:#3fa45b;--sapChart_Neutral:#848f94;--sapChart_Sequence_1:#5899da;--sapChart_Sequence_2:#e8743b;--sapChart_Sequence_3:#19a979;--sapChart_Sequence_4:#ed4a7b;--sapChart_Sequence_5:#945ecf;--sapChart_Sequence_6:#13a4b4;--sapChart_Sequence_7:#525df4;--sapChart_Sequence_8:#bf399e;--sapChart_Sequence_9:#6c8893;--sapChart_Sequence_10:#ee6868;--sapChart_Sequence_11:#2f6497;--sapChart_Sequence_Neutral:#848f94;}'}};\n//# sourceMappingURL=parameters-bundle.css-fb5a25ab.js.map\n
```

Console Output
![image](https://user-images.githubusercontent.com/14982812/163681670-a5630ba9-4d4c-4ec6-b7d9-e337bd6e98f5.png)

**Describe the solution you'd like**

One way to work around this would be to respect / consider the `browser` field of the `package.json` as described by @petermuessig [here](https://github.com/ui5-community/ui5-ecosystem-showcase/pull/595#issuecomment-1092470928). For example, this is already done in the bundling step by Rollup [here](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/2df84da78682b4ad303c997fc80e063f7fd54f1c/packages/ui5-tooling-modules/lib/util.js#L91-L94). 

In the UI Integration Card case this would probably not work. What I could think of is allowing the dependencies to be parsed by espree via adding the `sourceType: "module"` option. This however could also have negative implications down the road and is probably also not a "solution" and rather a workaround.

**Describe alternatives you've considered**

I'm not yet that familiar with everything going on regarding dependencies in the JS ecosystem. I've tried out a few things as also bundling up the `.cjs` and letting it get resolved by Rollup as the [node resolve plugin](https://www.npmjs.com/package/@rollup/plugin-node-resolve) being used in this extension already does consider this field and therefore is able to package it properly in my case. However as @mauriciolauffer rightfully mentioned [here](https://github.com/ui5-community/ui5-ecosystem-showcase/pull/595#issuecomment-1089843390) this is not a feasible long-term solution and could lead to various issues down the road if this would be added for everyone. 

**Additional context**

Some things related to this, were discussed here https://github.com/ui5-community/ui5-ecosystem-showcase/pull/595

If time allows I'll look into how this can be achieved as well but I lack the experience here to propose a proper working solution for now. I also fear breaking more things and wasting the time of others in the process. 😅

Would be nice to have this in the long term though.

**Comment by petermuessig** [comment]
Hi @wridgeu ,

I enhanced the `ui5-tooling-modules` a bit further to ignore those 3rd parties which cannot be transpiled and converted to UI5 AMD like modules. This will prevent the issue to appear in the generation of the app using the `marked` dependency: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/603

This is just one step ahead - the release of the fixed version will happen asap.

Cheers,
Peter

**Comment by petermuessig** [comment]
One more is coming - finally finished a feature which is pretty interesting for embedded scenarios, e.g. in FLP:
https://github.com/ui5-community/ui5-ecosystem-showcase/pull/605

This feature allows to generate the `sap.ui.loader.config` with the path mappings for the bundled resources! With that the app can also run inside an FLP without changes.

**Comment by wridgeu** [comment]
Hey @petermuessig 

> [...] This is just one step ahead [...]

Cool, why didn't I think of that! 😄 This fixes the issues at build time. I can make the consumption of marked work now by using the Shim + `sap.ui.loader.config`, nice! I also don't have issues with the integration cards anymore. 😊

> This feature allows to generate the `sap.ui.loader.config` with the path mappings for the bundled resources! With that the app can also run inside an FLP without changes.

That's awesome! In the case of marked it won't work (as `getResource` and the following `require.resolve` will continue to resolve to `.cjs`). If someone has more dependencies of this kind, maybe some kind of exclusion mechanism(config) would be nice so one could remove them from being considered for this bundling or an alternative mapping/root could be handed into the tooling, not sure. Maybe I misinterpret the intention a bit though. 😅 Looks nice and the marked thing aside, it looks like it'll work well. 🥳

I'll close this issue in a few days then, if there is nothing else. Thank you tons, much appreciated! :)

**Comment by petermuessig** [comment]
@wridgeu - please keep it open to follow up on the `browser` idea

And don't feel bad to comment issues or PRs - this is a valuable contribution! 😉

**Comment by petermuessig** [comment]
The latest version of the `ui5-tooling-modules` => `0.6.0` now has a better support for bundling OSS. Should not be needed anymore.
