### ISSUE TITLE
Later Versions of xmldom 0.6.0 have not not been updated in ui5-task-i18ncheck

### ISSUE THREAD

**Issue by nsahadev1** [ui5-community/ui5-ecosystem-showcase#613]
Hello team,

We would like to upgrade xmldom to version 0.7.0 as part of security vulnerability fix,

the latest version of xmldom is updated in the [npm repo](https://www.npmjs.com/package/@xmldom/xmldom).

could you update your library.

Regards,
Navin

**Comment by vobu** [comment]
knock yourself out and cut a Pull Request :)

**Comment by petermuessig** [comment]
Hi Navin,

looking for `xmldom` I don't see a higher version than `0.6.0`:
https://www.npmjs.com/package/xmldom

BR, Peter

**Comment by petermuessig** [comment]
Ah, ok, got it: https://www.npmjs.com/package/@xmldom/xmldom - I didn't check the link properly... 

Update requires to modify `package.json`: 

```
  "dependencies": {
    "@ui5/logger": "^2.0.1",
    "@xmldom/xmldom": "^0.8.2"
  },
```

and the `utils.js`:
```
const xmldom = require("@xmldom/xmldom");
```

Do you know out of your mind whether it is compatible?
