### ISSUE TITLE
Couldn't bundle plugin xlsx

### ISSUE THREAD

**Issue by bsehp** [ui5-community/ui5-ecosystem-showcase#623]
**Describe the bug**
Hello,

I am using SAP BAS to create an app which uses the npm module xlsx. 
The npm package xlsx does not get bundled during build process. I first openend an issue at the [ui5-tooling](https://github.com/SAP/ui5-tooling/issues/628) repo which was closed and it was recommended to open it here first.

`npm run build `

results in:

![image](https://user-images.githubusercontent.com/69502388/173770498-a7d60fca-fb17-49c5-8c54-12527e489e7e.png)

**To Reproduce**
1. create empty ui5 app in BAS
2. install npm modules ui5-tooling-modules & xlsx
packages.json looks like:
![image](https://user-images.githubusercontent.com/69502388/173770884-b97d86e5-dbb4-4aa8-8401-f19f66c3fe57.png) ui5.yaml looks like:
![image](https://user-images.githubusercontent.com/69502388/173771020-c91dc3b3-4c17-4304-ad0a-ad2a47bb2fb4.png)

3. add xlsx in View1.controller.js
![image](https://user-images.githubusercontent.com/69502388/173771277-3b0f32cc-7550-4e6d-8dcb-636e62625aa0.png)

**Expected behavior**
Plugin xlsx get bundled during build process

**Comment by petermuessig** [comment]
I'll check it in my next spare time...

**Comment by marianfoo** [comment]
I also noticed this problem with other libraries (Octokit, Firebase) on a [project of mine](https://github.com/marianfoo/gh-following-to-rss) with the same error.
I was able to solve it, but I am not so happy with the current solution, but it works ;)
https://github.com/marianfoo/gh-following-to-rss/blob/b321991aa6d5d69e6c88935a64decd3f38bc42fe/src/index.html#L50-L53
https://github.com/marianfoo/gh-following-to-rss/blob/b321991aa6d5d69e6c88935a64decd3f38bc42fe/src/index.html#L11-L13


I guess it can also have something to do with that https://github.com/ui5-community/ui5-ecosystem-showcase/issues/602

**Comment by SheetJSDev** [comment]
@bsehp the `xlsx` package ships with standalone browser scripts as well as a CommonJS and ESM build.

From our notes, some users have uploaded the standalone script (https://cdn.sheetjs.com/xlsx-0.18.9/package/dist/xlsx.full.min.js) using the SAP WebIDE, added the script as a resource, and referenced the standalone script directly through the `sap.ui.define` call.  A cursory search on the SAP site revealed https://blogs.sap.com/2017/04/30/how-to-include-third-party-libraries-modules-in-sapui5/ which is more or less the same approach.

**Comment by petermuessig** [comment]
The root cause of the issue has been found and is related to the lookup of the Node built-ins in the chain of the rollup plugins. I fixed this with the linked PR and will release an update of the extension soon.

**Comment by petermuessig** [comment]
Fixed with `ui5-tooling-modules` version `0.5.0`

**Comment by petermuessig** [comment]
Use 📦  `ui5-tooling-modules@0.5.1`
