### ISSUE TITLE
[ui5-tooling-modules] Adding chart.js to CAP application with fiori freestyle frontend and local testing

### ISSUE THREAD

**Issue by nocin** [ui5-community/ui5-ecosystem-showcase#633]
**Describe the bug**

I'm trying to find the correct way to use NPM packages (in this case chart.js) in my Fiori Freestyle Application when testing with `cds watch` in the Business Application Studio.
When following the [documentation ](https://www.npmjs.com/package/ui5-tooling-modules) or this [guide ](https://github.com/SAP-samples/ui5-typescript-tutorial/tree/main/exercises/ex8)I get the error mentionend below.
It seems it is not trying to find the chart.js package in the local ressources. 

**To Reproduce**

Create simple CAP project using the BAS:
```
cds init bookshop
cd bookshop
cds add samples
npm install
```
After that I added a Fiori Freestyle application using the Template Wizzard and used as backend my local CAP Project.
Runnning `cds watch` successfully starts the application.

Now the important part. Following the ui5-tooling-modules [documentation](https://www.npmjs.com/package/ui5-tooling-modules) I installed the ui5-tooling-modules package and also updated my `package.json` and `ui5.yaml`. After that I installed the chart.js library and added it to my controller like it is described in the Usage section. 
When now running `cds watch` I receive the error:
`'chart.js.js': failed to load 'chart.js.js' from https://sapui5.hana.ondemand.com/1.102.1/resources/chart.js.js: script load error`
I guess the absolute source path leads to this error?! But what do I have to change to get this running?

**Expected behavior**

chart.js is useable when adding it to the controller.

**Screenshots**

The full error from the browser console:
![grafik](https://user-images.githubusercontent.com/35531968/176431722-98cb3f7f-9284-4738-a949-b809d88375f0.png)

The generated resource path in the index.html:
![grafik](https://user-images.githubusercontent.com/35531968/176433419-f7401b47-9625-418c-ab88-8642a24e8ae5.png)

Thanks & Regards
Nico

**Comment by petermuessig** [comment]
Hi Nico,

did you try the option `prependPathMappings` already?
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-tooling-modules/README.md?plain=1#L36-L37

It adds the path mappings for the 3rd party. There are also even further plans and a PR is in progress to copy the 3rd parties into a specific namespace underneath the application. Then no path mappings would be needed anymore. But still WIP.

I'm closing the issue - you can re-open if the suggested solution doesn't work.

HTH and BR,
Peter

**Comment by nocin** [comment]
Hi Peter,

I'm not sure if I unterstand the `prependPathMappings` correctly but is it only used when running a app in a (Sandbox) Launchpad?! May be this is my misunderstanding. Does the whole thing only works when using a (Sandbox) Launchpad as it will provide the sapui5 libraries locally? 

When using `cds watch` the application is always started using the `index.html`. So I was expecting the deault value false would be fine.

Thanks & Regards
Nico

**Comment by nocin** [comment]
Hi Peter,

as I'm not able to reopen it my issue (I think because I cannot re-open my own issue if a repo collaborator closed it), just a new comment as notification. :-)

BR
Nico

**Comment by petermuessig** [comment]
You can in any case use `prependPathMappings=true`

**Comment by nocin** [comment]
Hi @petermuessig,

thank you for the explanation! 
When creating a plain new ui5 application everything is fine and the chart.js library is loaded while testing i.e. with `npm run np-flp`. Also the build process works fine.

But when building a CAP Application usually you start the App using `cds watch` and then opening the `index.html`. Can it be that this way the ui5.yaml is not used as you are not starting the application using the fiori tools? 
Or is `cds watch` using the fiori tools under the hood when it detects a freestyle application?
![grafik](https://user-images.githubusercontent.com/35531968/179476285-8badf014-5ab0-4540-a191-799d353d0016.png)


BR
Nico

**Comment by nocin** [comment]
Hi @petermuessig,

just a little ping. :-)
