### ISSUE TITLE
Third party library is requested from https://ui5.sap.com/1.99.4/resources/xlsx.js

### ISSUE THREAD

**Issue by bsehp** [ui5-community/ui5-ecosystem-showcase#638]
**Describe the bug**
When deploying a ui5 app to abap backend a thirdparty is not found. 

**To Reproduce**
1. create empty ui5 app in bas
2. install npm modules ui5-tooling-modules & xlsx
3. add library to controler (sap.ui.define "xlsx" & function (Controller, XLSX)
4. deploy to abap server (steampunk)
5. when loading the app xlsx is requested from https://ui5.sap.com/1.99.4/resources/xlsx.js and not found

**Expected behavior**
Load library from local path.

**Additional context**
screenshots of config files like here
https://github.com/ui5-community/ui5-ecosystem-showcase/issues/623

**Comment by petermuessig** [comment]
Hi @bsehp .

same question like #633

Did you try the option prependPathMappings already?
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-tooling-modules/README.md?plain=1#L36-L37

It adds the path mappings for the 3rd party. There are also even further plans and a PR is in progress to copy the 3rd parties into a specific namespace underneath the application. Then no path mappings would be needed anymore. But still WIP.

The `prependPathMappings` works standalone and also for the FLP. The `prependPathMappings` will add sap.ui.loader.config entries to your `Component.js` before the `sap.ui.define` for every used OSS. This will ensure to configure the UI5 loader to load xlsx.js from your application rather the UI5 distribution.

I'm closing the issue - you can re-open or contact me again if the suggested solution doesn't work.

BR,
Peter

**Comment by bsehp** [comment]
This works. Thanks again!
