### ISSUE TITLE
[ui5-middleware-cfdestination] does not work when serving with --h2

### ISSUE THREAD

**Issue by piejanssens** [ui5-community/ui5-ecosystem-showcase#641]
**Describe the bug**
```
Error: write EPROTO 4376790400:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**To Reproduce**
1. Use ui5-middleware-cfdestination
2. Run with `ui5 serve --h2`
3. See error

**Comment by petermuessig** [comment]
@vobu - are you aware of this?

**Comment by vobu** [comment]
now I am, sorry 😮‍💨 
probably an issue w/ the dependencies of the middleware. I'll try looking into it the next couple of days, but would really be grateful for a hand here *nudge nudge* @piejanssens 😄

**Comment by piejanssens** [comment]
I think we'll have to swap out `request` for `fetch-h2`.
