### ISSUE TITLE
[ui5-tooling-modules] Adding chart.js to CAP application with fiori freestyle frontend and local testing

### ISSUE THREAD

**Issue by nocin** [ui5-community/ui5-ecosystem-showcase#646]
Hi @petermuessig,

as I'm not allowed to reopen a closed issue and you properly will not see my response in the closed one, I'm opening a new one here.

Reference: #633 

BR,
Nico

**Comment by petermuessig** [comment]
@nocin - any update? Can we close the issue?

**Comment by nocin** [comment]
Hi @petermuessig,

thanks for your answer. I think I have understood so far. I guess when deployed in CF, the app runs via ui5 tooling and it's only a problem when testing locally?
I'm unfortunately a bit busy right now so I haven't had time to test yet.

And sorry for opening a second issue. Perhaps the repo settings can be changed, that issue creators are allowed to reopen their issue? Or does the default behavior of Github prevents this? :-)

I'm closing this issue and will post here again when running into problems.

Thanks & BR
Nico

**Comment by nocin** [comment]
Hi @petermuessig,

seems like the new [cds-plugin-ui5](https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/cds-plugin-ui5) is exactly what I was missing all the time.

Thanks!
Nico
