### ISSUE TITLE
[ui5-middleware-cfdestination] issues with mTLS (certificates) backends

### ISSUE THREAD

**Issue by SCHRJE1** [ui5-community/ui5-ecosystem-showcase#647]
Hi colleagues.

When connection via the _ui5-middleware-cfdestination_ module with an existing _default-ev.json_ and _xs.app.json_.
In the console, the _certurl_ provided in the xsauaa credential section is overwritten by a hard-coded url: https://authentication.cert.sap.hana.ondemand.com/oauth/token and the _certurl_ mentioned in the _default-env.json_ will not be considered.

Same, we figured out, if we implemented a local approuter with same settings. with an older version >=8.x it works fine! An newer version >9.x is not working and has the same behavior. Maybe someting with the approuter module?

Thanks and regards!

**Comment by vobu** [comment]
yeah, i hear you! well, if only the `@sap/approuter` would be Open Source so we could check out whether there's a bug in it with the behavior you describe...if only... 😢 😭 
@tobiasqueck: can your relay to Katja, Tobias S. or whomeverItMayConcern™ please?

**Comment by sergioRozenszajn** [comment]
Hi,
The code in approuter that does it is:
if (uaaOptions.certurl) {
    let hostname = url.parse(uaaOptions.certurl).hostname;
    let certDomain = hostname.slice(hostname.indexOf('.') + 1);
    let tenantCertHost = (tenant ? tenant + '.' : '') + certDomain;
    uaaOptions.certurl = toUrlString(url.parse(uaaOptions.certurl), tenantCertHost);
  }

It just replaces the tenant in the certurl by the actual tenant. I don't think it hardcodes something. Please provide your approuter github repository so we can check.

Thanks, Sergio

**Comment by petermuessig** [comment]
Issue seems to be related to the AppRouter rather than the middleware. As there is no follow-up till today, I'll close it.
