### ISSUE TITLE
Getting required is not defined when using ssh2 node library in UI5 framework

### ISSUE THREAD

**Issue by ramanareddy438** [ui5-community/ui5-ecosystem-showcase#649]
I am trying to use the node library ssh2 in the UI5 project. But I am getting the required is not defined at line ssh2.js as shown in the following screenshot. Please help if there are any alternatives to fixing the issue.

![image](https://user-images.githubusercontent.com/7078863/201856982-f3dd0d11-e355-4959-8a2d-765700275a93.png)

**Comment by petermuessig** [comment]
Hi @ramanareddy438 ,

as explained in my answer in the blog, this is a limitation of the ssh2 library which requires native code and thus cannot be used at client side.

https://stackoverflow.com/questions/42799888/can-you-use-the-node-package-ssh2-in-a-browser

Sorry for having no better news.

**Comment by ramanareddy438** [comment]
Thank you Peter. I submitted the ticket before seeign your answer. I understand.
