### ISSUE TITLE
[ui5-tooling-transpile] Misleading console errors when using ui5-tooling-transpile-middleware

### ISSUE THREAD

**Issue by tobiasqueck** [ui5-community/ui5-ecosystem-showcase#650]
**Describe the bug**
The bug was originally reported at https://github.com/SAP/open-ux-tools/issues/764. It actually consists of two separate but related issues.

**(1) Component-preload.js**

When running the generated TS app as part of a local FLP instance for testing, then the shell tries to load a `Component-preload.js` file. The middleware tries to find a not existing `Component-preload.ts` file that doesn't exist. Based on the `README.md` this can be prevented by adding `Component-preload.js` to the `excludePatterns` array. However, it doesn't work, it only works if you add a leading `/` so in this case `/Component-preload.js` which doesn't match the documentation

**(2) Mixed JS/TS project**
If you

**To Reproduce**
1. Generate a typescript app with the SAP Fiori tools
2. Add the `Component-preload.js` to the `excludePatterns` array
3. Add a new JS file e.g. `webapp/myJsFile.js`
4. Start the preview, and in the browser try open
5. http://localhost:8080/Component-preload.js
6. http://localhost:8080/myJsFile.js
7. See two errors

**Expected behavior**
No errors in the console.

**Screenshots**
![198076351-d3765675-da8d-4f77-aa6f-a200e8f4c6a9](https://user-images.githubusercontent.com/44933199/202124067-3c4efc53-e0a8-4476-a745-cd09f19b5cb6.png)

**Desktop (please complete the following information):**
Doesn't matter

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by tobiasqueck** [comment]
@petermuessig here are the issues that we just discussed on the phone.

**Comment by petermuessig** [comment]
Fix with latest version: https://www.npmjs.com/package/ui5-tooling-transpile `0.2.1`
