### ISSUE TITLE
[ui5-tooling-modules] Task failes as of UI5 CLI 3.0.0-rc.0

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/ui5-ecosystem-showcase#664]
**Describe the bug**
ui5-tooling-modules fail in ui5 cli v3.0

**To Reproduce**
1. Use `ui5-tooling-modules` with ui5 cli 3.0.0-rc.0

**Expected behavior**
As of v3.0, a custom task need a `determineRequiredDependencies` callback function to access `dependencies`.
See:
https://sap.github.io/ui5-tooling/v3/pages/extensibility/CustomTasks/#required-dependencies

**Comment by petermuessig** [comment]
@marianfoo - hmm, I don't see this issue locally. I used the UI5 CLI `3.0.0-rc.0` in the `ui5-app` and launched the application with pnpm dev. After fixing a small issue in the cfdestination middleware it worked. The cfdestination middleware is using internals of the UI5 CLI filesystem which has been changed with UI5 CLI V3.

**Comment by marianfoo** [comment]
yeah, i tried that there too and it worked for me too
it might be that custom task implementation here
https://github.com/marianfoo/ui5-cc-excelUpload/blob/593b009298bfc61c2bedce1e23573e96e8ff9e3a/ui5-build.yaml#L12-L18

i think the problem is solved anyway with the new version
https://github.com/SAP/ui5-tooling/issues/732
