### ISSUE TITLE
[ui5-tooling-modules] Something wrong from 0.7.1 to 0.7.2

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/ui5-ecosystem-showcase#673]
When updaten ui5-tooling-modules from 0.7.1 to 0.7.2, something is going wrong.
The wrong content is read from a npm package.

**To Reproduce**
1. `git clone https://github.com/marianfoo/ui5-cc-excelUpload`
2.  update `ui5-tooling-modules` to `0.7.2`
3. `pnpm i`
4. `npm run build`
5. See file `dist/thirdparty/xlsx.js` not the file like `node_modules/xlsx/xlsx.js`

**Expected behavior**
Full file like `node_modules/xlsx/xlsx.js` is in dist folder

**Screenshots**
in `task.js`
<img width="701" alt="image" src="https://user-images.githubusercontent.com/13335743/210641599-2180c543-bc08-42cf-9764-a4265b0e40c7.png">

**Desktop (please complete the following information):**
 - OS: Windows/Macos
 - Version node v18.21.1

**Comment by cpf-hse** [comment]
@marianfoo Is your firebase setup still working?

I get an error about a missing factory. Will add details later here for steps to reproduce.

**Comment by petermuessig** [comment]
@marianfoo , @cpf-hse : 
the issue is related to the update of the `@rollup/plugin-node-resolve` dependency to version `15.0.1`. What's a bit strange is, that in my project it works and in your project it doesn't work. In the Ecosystem Showcase I have the dependency to `xlsx` and `firebase` as part of the `Thirdparty` view of the `ui5-app`. There it works and here it doesn't... 😒

**Comment by marianfoo** [comment]
yeah, i tried that too and worked for me too

but it does not work with https://github.com/marianfoo/gh-following-to-rss either
1. `git clone https://github.com/marianfoo/gh-following-to-rss`
2. update `ui5-tooling-modules` to ´0.7.2´
3. `npm i`
4. `npm run build:self`
5. `npm run start:dist`

**Comment by petermuessig** [comment]
Rolled back the version of `@rollup/plugin-node-resolve` to 13.3.0 which will solve the issue and released the new version of the `ui5-tooling-modules` 0.7.3
