### ISSUE TITLE
[ui5-middleware-cfdestination] not-GET requests getting ignored

### ISSUE THREAD

**Issue by drvup** [ui5-community/ui5-ecosystem-showcase#689]
**Describe the bug**
Since one of the last versions it's not possible anymore to send not-GET requests via the ui5-middleware-cfdestination. I guess it's related to this [commit](https://github.com/ui5-community/ui5-ecosystem-showcase/commit/e9ab783f9d72fd6d043a566938e4c5baf73d93f0#diff-86bb328c5d0806a703667d101afc1ffdd3dd54e625a5a0825e89a721f9b2c823)

**To Reproduce**
Use the latest version, 0.10.8, of `ui5-middleware-cfdestination` and try to do a not-GET request, e.g. a POST request, to a destination with the proxy functionality. You'll get a http-status 404 as it's not existing because the proxy only deals with GET requests right now :) 

**Expected behavior**
POST is also working, not only for changes on the source-/targetsystem, also to continue using BATCH functionalities 

**Additional context**
I am using ui5-tooling v3 -> @ui5/cli@3.0.2

By the way, thanks to all the great things you deliver and support. Special thanks to @petermuessig who is taking care of this great middleware - I do share and implement it in every project first :D ... though life to teach others getting rid of maven compilers - but with these kind of extensions it's a dealbreaker and most often the reason they do except - so many thanks to you and all the other contributors!

**Comment by petermuessig** [comment]
@drvup - thanks for your nice feedback!

I'll take a look the next days. I was thinking of reusing the simpleproxy middleware under the hood to save double code bases for similar stuff.

**Comment by petermuessig** [comment]
@drvup - fix will be included in `ui5-middleware-cfdestination` in version `0.10.9`
