### ISSUE TITLE
[ui5-tooling-modules] Usage in combination with local approuter

### ISSUE THREAD

**Issue by ThomasSwolfs** [ui5-community/ui5-ecosystem-showcase#694]
**Describe the bug**
Is there a way to make this work with localapprouter?

**To Reproduce**
1. Create a Project with a localapprouter and 2 ui5 modules
2. Use ui5-tooling-modules in both ui5 applications and import npm libraries
3. Run the localapprouter on port 5000
4. Serve both ui5 apps. (For example, port 8080 & 8081)
5. Provide 2 destinations in default-env.json. One for each ui5 app that is being served
6. Add routes to both applications in xs-app.json of the local approuter.

**Expected behavior**
When running the approuter locally, I would expect that both ui5 apps should be accessible and loading their own node modules with the help of ui5-tooling-modules.

The middleware is loading the modules from path /resources, resulting in URL localhost:5000/resources/... instead of localhost;8080/resource OR localhost:8081/resources.

I solved this by creating an empty ui5 application containing all the relevant node modules. Then I created a destination for this application & added a route with the following config:

```
{
			"source": "^/resources/(.*)$",
			"target": "/resources/$1",
			"authenticationType": "xsuaa",
			"destination": "modules"
		},
```

This way, both UI5 resources and node modules will be fetched from this 'dummy' container. Because of this, each npm module used in any UI5 app in this project needs to be duplicated to this 'dummy' container.

I think there should be an easier way to fix this..
One solution could be to add an optional parameter to the library which results into a prefix.
For example:
App1 -> will search for localhost:5000/app1/resources/
App2 -> will search for localhost:5000/app2/resources/

If this would be the case, we could create following routes in the approuter:

```
 {
	"source": "^/app1/resources/(.*)$",
	"target": "/resources/$1",
	"authenticationType": "xsuaa",
	"destination": "app1"
},
 {
	"source": "^/app2/resources/(.*)$",
	"target": "/resources/$1",
	"authenticationType": "xsuaa",
	"destination": "app2"
},
 {
	"source": "^/resources/(.*)$",
	"target": "/resources/$1",
	"authenticationType": "xsuaa",
	"destination": "UI5Resources"
},

```

Any suggestions here?

Kind regards,
Thomas

**Comment by petermuessig** [comment]
Strange, for me it works - I just extended the local setup of the ecosystem. I start the AppRouter via cfdestination middleware but then access the UI5 app via the AppRouter port 1091. The AppRouter proxies the content from the App similar as you sketched it above - and voila the resources created by the tooling modules middleware is returned - see #695

**Comment by ThomasSwolfs** [comment]
Hi @petermuessig

Thanks for the reply!

I got your example working indeed, but our setup is slightly different.

We don't use the cfdestination middleware. In our setup, we are running the approuter separately with it's own xs-app.json file.

![image](https://user-images.githubusercontent.com/9072117/225270937-559b83fd-4ae6-4af8-9fff-503dfc029938.png)


Also, we have a local launchpad in which we  define where the resources are coming from:

![image](https://user-images.githubusercontent.com/9072117/225271383-a74aecc1-47f6-4df0-89d2-96f9bc7f9f6b.png)


Our UI consists of different UI5 apps which are served separately on different ports, each using the ui5tooling-modules.


When navigating to the applications directly, the middleware will do it's work and the resources and npm libraries will be correctly loaded.
But when starting from the approuter, all resources will be called via localhost:5000/resources. Because of this, the approuter doesn't know the difference between:
- SAP resource
- NPM resources for ap1
- NPM resources for app2



Maybe It's not possible to achieve this with our current setup & we might need to check the possibilities with cfdestination middleware..

**Comment by petermuessig** [comment]
If it works with the cfdestination it should also work with the plain approuter. I think there is a config issue somewhere. Need to create a local setup for this to verify it...

**Comment by petermuessig** [comment]
Sorry @ThomasSwolfs  - took a while to come back to this topic - here a standalone example:
https://github.com/ui5-community/ui5-ecosystem-showcase/pull/718
