### ISSUE TITLE
[ui5-tooling-modules] Certain Shims not working since ui5-tooling-modules version 0.7.12

### ISSUE THREAD

**Issue by Talwynox** [ui5-community/ui5-ecosystem-showcase#724]
## Expected Behavior
The build should complete successfully with version 0.7.12, with no errors related to the handling of shim projects.

## Current Behavior
When upgrading from version 0.7.10 to version 0.7.12, the build process fails due to the incorrect handling of some shim projects. This issue seems to have been caused by a change in the Rollup version from 3.17.2 to 3.20.0.

## Steps to Reproduce the Issue
1. Create UI5 App with ui5-tooling-modules: ^0.7.12
2. Add @stomp/stompjs (might also happen with other packages) as shim
3. Add a component which imports stompjs
4. run ui5 build

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `3.0.3`
 * Node.js Version: `v18.12.1`
 * npm Version: `9.6.1`
 * OS/Platform: `win10`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
`error lbt:bundle:Resolver **** error: missing module @stomp/stompjs.js, required by .../messageQueue/ConnectionStomp.js`

**Comment by petermuessig** [comment]
Hmm, this rollup drives me crazy... 😅  I'll take a look...

**Comment by petermuessig** [comment]
Can you test with:
`"ui5-tooling-modules": "^0.9.3"`

Unfortunately, the minor updates in the 0 major version are considered as major version upgrades.

**Comment by Talwynox** [comment]
Version `0.9.3` does not work at at
It always fails with 
`Cannot find module 'ignore-walk'`
Version `0.9.4` fails with the same error as `0.7.13`

**Comment by petermuessig** [comment]
I updated the project to UI5 Tooling V3 and it still works for me. I attached my project here:
[com.myorg.myapp.zip](https://github.com/ui5-community/ui5-ecosystem-showcase/files/11218976/com.myorg.myapp.zip)

**Comment by petermuessig** [comment]
Thx @Talwynox for the sample project - I missed to look at a small detail:

The build result using 0.7.10:

```sh
info my.projects.test › Running task minify...
info my.projects.test › Running task generateFlexChangesBundle...
info my.projects.test › Running task generateStandaloneAppBundle...
error lbt:bundle:Resolver **** error: missing module sap/ui/support/Bootstrap.js, required by sap/ui/core/Core.js
error lbt:bundle:Resolver **** error: missing module sap/ui/testrecorder/Bootstrap.js, required by sap/ui/core/Core.js
error lbt:analyzer:JSModuleAnalyzer Unhandled AST node type MetaProperty Node {
  type: 'MetaProperty',
  start: 51842,
  end: 51852,
  meta: Node { type: 'Identifier', start: 51842, end: 51845, name: 'new' },
  property: Node { type: 'Identifier', start: 51846, end: 51852, name: 'target' }
}
error lbt:resources:ResourcePool Failed to analyze chart.js/auto.js: Unhandled AST node type MetaProperty
info my.projects.test › Running task transformBootstrapHtml...
info ProjectBuilder Build succeeded in 31 s
info ProjectBuilder Executing cleanup tasks...
```

The build result using 0.9.4:

```sh
info my.projects.test › Running task generateStandaloneAppBundle...
error lbt:bundle:Resolver **** error: missing module sap/ui/support/Bootstrap.js, required by sap/ui/core/Core.js
error lbt:bundle:Resolver **** error: missing module sap/ui/testrecorder/Bootstrap.js, required by sap/ui/core/Core.js
error lbt:analyzer:JSModuleAnalyzer Unhandled AST node type MetaProperty Node {
  type: 'MetaProperty',
  start: 51842,
  end: 51852,
  meta: Node { type: 'Identifier', start: 51842, end: 51845, name: 'new' },
  property: Node { type: 'Identifier', start: 51846, end: 51852, name: 'target' }
}
error lbt:resources:ResourcePool Failed to analyze chart.js/auto.js: Unhandled AST node type MetaProperty
error lbt:bundle:Resolver **** error: missing module @stomp/stompjs.js, required by my/libraries/lib1/Lib1Stomp.js
info my.projects.test › Running task transformBootstrapHtml...
```

This happens during the `generateStandaloneAppBundle` build step - but I need to investigate this further what the difference between those versions is. 

BTW: you do not need to mix Babel anymore with the tooling - you can easily combine them using the `ui5-tooling-transpile` tooling extension - maybe I can create a PR the next days for you which simplifies your project setup...

**Comment by Talwynox** [comment]
Thanks for the infos. 
Yes would appreciate a PR.

**Comment by petermuessig** [comment]
PR has been created in your repository - see link above - once merged this will close this issue! 😄
