### ISSUE TITLE
Cannot run the ui5 app. throwing Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by ponnagantianusha70** [ui5-community/ui5-ecosystem-showcase#736]
**Describe the bug**
It is throwing an error while running the app. The behavior is same even after reinstalling the npm by deleting the node-modules and package-lock.json
Error Message:
Cannot read properties of undefined (reading 'match')

**To Reproduce**
1.Ui5 app with following devDependencies in the package.json

"devDependencies": {
"@sap/ux-ui5-tooling": "1",
"@ui5/cli": "^2.14.1",
"eslint": "7.6.0",
"rimraf": "3.0.2",
"ui5-middleware-simpleproxy": "^0.9.3",
"ui5-task-nwabap-deployer": "1.0.15",
"ui5-task-transpile": "^0.3.1"
},

2. Run npm install

3. Execute command

**Expected behavior**
The app should be running on the localhost.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**
UI5 Module Version (output of ui5 --version when using the CLI): 1.71.53
Node.js Version: v18.14.0
npm Version: 9.4.2
OS/Platform: Windows
Browser (if relevant): unknown
Other information regarding your environment (optional): nothing

Stack Trace:
TypeError: Cannot read properties of undefined (reading 'match')
    at module.exports (file:******\node_modules\ui5-middleware-simpleproxy\lib\proxy.js:137:37)
    at customMiddleware (file:///*******/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:313:53)
    at async MiddlewareManager.addMiddleware (> file:///******/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:121:16)
    at async MiddlewareManager.addCustomMiddleware (file:///*******/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:295:4)
    at async MiddlewareManager.applyMiddleware (file:///*****/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:52:3)
    at async serve (file:///******/node_modules/@ui5/cli/node_modules/@ui5/server/lib/server.js:178:2) 
    at async serve.handler (file:///*******/node_modules/@ui5/cli/lib/cli/commands/serve.js:136:33)

**Comment by petermuessig** [comment]
Hi @ponnagantianusha70 , can you also please share your ui5.yaml?

**Comment by ponnagantianusha70** [comment]
Hi Peter

Here is my ui5.yaml

``specVersion: '2.1'
metadata:
  name: ************
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
server:
  customMiddleware:
   - name: ui5-middleware-simpleproxy
     afterMiddleware: compression
     mountPath: /sap/opu/odata/***/
     configuration:
      baseUri: "https://*******************/sap/opu/odata/***/"
      limit: "50mb"
      username: 
      password: 
      removeETag: true
      strictSSL: false
   - name: ui5-middleware-simpleproxy
     afterMiddleware: compression
     mountPath: /sap/bc/ui5_ui5/***/
     configuration:
      baseUri: "https://************************/sap/bc/ui5_ui5/***/"
      limit: "50mb"
      username: 
      password: 
      removeETag: true
      strictSSL: false
   - name: ui5-middleware-simpleproxy
     afterMiddleware: compression
     mountPath: /sap/public/bc/ui5_ui5/
     configuration:
      baseUri: "https://****************************/sap/public/bc/ui5_ui5/"
      limit: "50mb"
      username: 
      password: 
      removeETag: true
      strictSSL: false
   - name: ui5-middleware-simpleproxy
     afterMiddleware: compression
     configuration:
      port: 
      path: webapp
      delay: 300
   - name: fiori-tools-preview
     afterMiddleware: fiori-tools-appreload
     configuration:
      component: **********
      ui5Theme: sap_fiori_3

**Comment by petermuessig** [comment]
Hi @ponnagantianusha70 ,

the last middleware entry for the `ui5-middleware-simpleproxy` is missing the `baseUri`. Either remove the last entry or add the missing `baseUri`.

I also see in the code that the error handling can be improved. Will fix it soon. This line will be made more fail-safe:
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-simpleproxy/lib/proxy.js#L137

THX for reporting and BR,
Peter

**Comment by ponnagantianusha70** [comment]
It is working now. Thanks @petermuessig
