### ISSUE TITLE
[ui5-task-cachebuster] Update deprecated dependencies to their latest versions

### ISSUE THREAD

**Issue by Andromeda08** [ui5-community/ui5-ecosystem-showcase#770]
Hi Team!

While migrating our app from UI5 Tooling v2 to v3 we've noticed that the package `ui5-task-cachebuster` still depends on the old, now marked as deprecated `@ui5/fs@2.0.6` and `@ui5/logger@2.0.1` packages.

```
npm WARN deprecated @ui5/logger@2.0.1: UI5 Tooling version 2 is out of maintenance. Migrate your project to the latest version: https://sap.github.io/ui5-tooling/stable/
npm WARN deprecated @ui5/fs@2.0.6: UI5 Tooling version 2 is out of maintenance. Migrate your project to the latest version: https://sap.github.io/ui5-tooling/stable/
```

We would like to ask you - if possible - to update the packages dependencies to their latest versions.

Thank you!

**Comment by petermuessig** [comment]
Hi @Andromeda08 , for now, all of the tooling extensions are working with the UI5 Tooling V2 and V3 - therefore they still depend on the V2 dependencies. There is a plan to update all tooling extensions to V3 soon - please stay tuned...

**Comment by treee111** [comment]
thanks for working on this @petermuessig, we also noticed the same for package `ui5-middleware-servestatic`.
As you mentioned, probably most/all tooling extensions are affected.
