### ISSUE TITLE
[ui5-middleware-livereload] tries to load fioriSandboxConfig.json from localhost:35729 instead of localhost:8080

### ISSUE THREAD

**Issue by gregorwolf** [ui5-community/ui5-ecosystem-showcase#771]
**Describe the bug**

I've created the sample project [ui5-react-nest-hello-world](https://github.com/gregorwolf/ui5-react-nest-hello-world) using [generator-ui5-react-nest](https://github.com/aydin-ozcan/generator-ui5-react-nest). It adds the ui5-middleware-livereload to the ui5.yaml. When using the index.html all works fine. But I've changed the open parameter to "launchpad.html#helloworldui-display" so I can test the app in the local launchpad mock. But as long as I have the ui5-middleware-livereload active it tries to load the file fioriSandboxConfig.json from the URL: http://localhost:35729/shells/sandbox/fioriSandboxConfig.json. As this port is only the port for the livereload the state that I can see in the developer tools is pending:

![Screenshot 2023-07-24 at 09 31 56](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/2639535/3c04ca23-aee3-4e52-bbb2-4716e0ee9f20)

In the details of the request you can see the different port:

![Screenshot 2023-07-24 at 09 32 04](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/2639535/ea294df4-4cd5-4a5b-a77c-9cddbfe20aff)

**To Reproduce**

1. Clone 'https://github.com/gregorwolf/ui5-react-nest-hello-world'
2. Make sure you use Node.JS 18
3. Install the dependencies with 'pnpm i'
4. Run 'pnpm start:ui5'
5. Your default browser should open and a blank page will be shown
6. Stop 'pnpm start:ui5'
7. Comment all lines for the plugin in 'packages/helloworld/ui5.yaml'
8. Run 'pnpm start:ui5'
9. Your default browser should open and the app will be shown in the Launchpad

**Expected behavior**

The ui5-middleware-livereload should also work with the local launchpad mock.

**Desktop (please complete the following information):**

 - OS: MacOS Ventura 13.4.1
 - Browser Chrome 115.0.5790.98, Firefox 115.0.2, Safari 16.5.2 

**Additional context**

Safari behaves a bit different:

It does also the request to http://localhost:35729/shells/sandbox/fioriSandboxConfig.json but timeouts after 10 seconds. Then it tries http://localhost:8080/appconfig/fioriSandboxConfig.json
 and succeeds:

![Screenshot 2023-07-24 at 09 48 54](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/2639535/5fa45939-d762-430d-b5f7-f0e7b58edf21)

**Comment by petermuessig** [comment]
Hi @gregorwolf , created a PR to make it running:
https://github.com/gregorwolf/ui5-react-nest-hello-world/pull/1
