### ISSUE TITLE
[cds-plugin-ui5] Entities with 'where' clause restrictions are empty after installing the plugin

### ISSUE THREAD

**Issue by daniellelyle** [ui5-community/ui5-ecosystem-showcase#772]
After installing `cds-plugin-ui5` in a CAP project, an entity with a 'where' clause restriction is not populated with data. 

For example:

```
entity Orders @(restrict: [
    { grant: 'READ', to: 'Auditor', where: 'country = $user.country' },
  ]) {/*...*/}
```

The resulting data: 

```
{
"@odata.context": "$metadata#Orders",
"value": []
}
```

**After removing the plugin** and reinstalling the node modules, the data shows up again as expected.

I'm not sure if this is an issue with the plugin itself, with CAP, or a combination of the two, but since it works as expected without the plugin, I thought it best to start here. Thanks in advance!

**Comment by petermuessig** [comment]
Hi @daniellelyle , can this be easily reproduced with the cap-sflight project? It would be easier to identify the root cause. Thanks...

**Comment by petermuessig** [comment]
Is there maybe the `@(requires:'authenticated-user')` missing for the entity `Orders`? But I'm wondering why it works without the CDS plugin? AFAICS, the `$user` requires an authenticated user: https://cap.cloud.sap/docs/node.js/authentication#user-id - but I'm not aware of the `country`

@chgeo @danjoa - maybe you have an idea here?

**Comment by daniellelyle** [comment]
> Hi @daniellelyle , can this be easily reproduced with the cap-sflight project? 

Hi @petermuessig, sorry for the late reply. Yes, I did manage to reproduce this with the cap-sflight project. But your comment led me in the right direction - what the sflight app had that ours didn't was an additional `@restrict` annotation granting READ access to an authenticated user.

Adding this annotation in addition to our already existing `@requires` annotation (I guess we need to explicitly give READ access)  fixes the problem. Thanks so much for your help!

**Comment by petermuessig** [comment]
Hi @daniellelyle , the CDS plugin doesn't do anything special for the CAP server itself. It just attaches the UI5 applications in custom routes into the CAP express server. I think this question needs to be clarified with the CAP team (@chgeo, @danjoa) may help to clarify this. I try to reach out to them...

**Comment by chgeo** [comment]
Not sure what the issue is.
Please provide a link to your source code with which we can reproduce the effect.

**Comment by daniellelyle** [comment]
@chgeo thanks so much for getting back to me. I looked into it further with the sflight application and it seems to be okay once the permissions are adjusted as mentioned above. Following the exact same structure in our application does not work. In any case, since it is working as expected within the sflight application we can assume there is something missing on our end. I'll close this issue. Thanks again for your attention.
