### ISSUE TITLE
[ui5-tooling-transpile] version ^3.0.0 does not handle tsconfig.json files with comments or trailing commas

### ISSUE THREAD

**Issue by sven-petersen** [ui5-community/ui5-ecosystem-showcase#803]
**Describe the bug**

The ui5-tooling-transpile@^3.0.0 task and middleware fail with the error below if the tsconfig.json contains comments or trailing commas. The Typescript compiler itself allows both and it would be great of it would be supported by this tool as well.

```jsonc
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "noImplicitAny": true,
    "rootDir": "webapp",
    "outDir": "build/ui", // note the trailing "," here
    // some comment
  },
  "include": ["./webapp/**/*", "./global.d.ts", "./webapp/**/*.json"],
  "exclude": ["node_modules"],
  "references": []
}

```

**To Reproduce**

Create a `tsconfig.json` with comments and/or trailing commas

**Expected behavior**

The task and middleware should not fail.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A

**Additional context**

**Comment by petermuessig** [comment]
Good catch - fix is on its way!
