### ISSUE TITLE
Add example for `dev-approuter` + remove `path` dep from `dev-approuter`

### ISSUE THREAD

**Issue by petermuessig** [ui5-community/ui5-ecosystem-showcase#826]
You can use the newly added bookshop examples for the dev-approuter showcase...

**Comment by petermuessig** [comment]
This dependency is obsolete:
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/dev-approuter/package.json#L17

**Comment by nicoschoenteich** [comment]
🚀
