### ISSUE TITLE
[dev-approuter] Option to run linked CDS App --with-mocks

### ISSUE THREAD

**Issue by BenReim** [ui5-community/ui5-ecosystem-showcase#845]
**Describe the bug**
Depending on the scenario, it can be desired to launch the CDS server with mocking features.

In a CAP project, either the command `cds watch` or alternatively `cds serve all --with-mocks` would [mock an external system](https://cap.cloud.sap/docs/get-started/jumpstart#mocked-platform-services) if no credentials are provided, i.e. there is no `credentials` section in the `cds.requires.MyExternalService`.

**To Reproduce**
Launching the `dev-approuter` with a CAP Profile (through CDS_ENV) that references an external service (without credentials section) currently throws: 
```shell 
Error: No credentials configured for "MyExternalService".
```

**Comment by petermuessig** [comment]
Hi @BenReim , can you share an example for this?

**Comment by petermuessig** [comment]
@BenReim you can also reach out directly to me for an example. I need to see this... THX
