### ISSUE TITLE
[ui5-task-compileless] Filename pattern clash

### ISSUE THREAD

**Issue by grahamrobbo** [ui5-community/ui5-ecosystem-showcase#889]
**Describe the bug**
I have a UI5 app that consists of multiple nested components stored in a "reuse" folder under the application root directory - webapp. My directory structure with *less files looks like this...

```
webapp/css/style.less
webapp/reuse/component1/css/style.less
webapp/reuse/component2/css/style.less
...
```

The compileless task successfully compiles all the *.less files except the one directly under the application root directory. This is because the file pattern "/css/style.less" matches with every other resource. This match happens at [line 94
](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/198b4ee18e4fee3dc30226c82bb9a990ec0c3903/packages/ui5-task-compileless/lib/compileLess.js#L94).

**To Reproduce**
1. Download and extract the [Routing Nested Component demo from the OpenUI5 SDK
](https://sdk.openui5.org/entity/sap.ui.core.routing.Router/sample/sap.ui.core.sample.RoutingNestedComponent)
2. Rename all the `css/style.css` files to `css/style.less`
3. Define `ui5.yaml` like so ... 

```  
builder:
  customTasks:
    - name: ui5-task-compileless
      afterTask: replaceVersion
      configuration:
        debug: true
        lessToCompile:
          - "**/*.less"
```
4. Perform `ui5 build` and note `dist/css/style.css` is not created. Rename `webapp/css/style.less` to `test.less` and it works.

**Comment by petermuessig** [comment]
@grahamrobbo - thanks for the steps to reproduce - I can debug the issue now - this coding needs a bit of a refresh - quite oldish, even though I reworked it a bit for 3.0... :-D

**Comment by petermuessig** [comment]
Fix is about to be released...
