### ISSUE TITLE
[ui5-middleware-serveframework] proxy not passed?

### ISSUE THREAD

**Issue by wozjac** [ui5-community/ui5-ecosystem-showcase#890]
Hello,

we are using a corporate proxy. Currently the middleware does not work - connection timeout for the below request:

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/198b4ee18e4fee3dc30226c82bb9a990ec0c3903/packages/ui5-middleware-serveframework/lib/index.js#L66

After changing to:
```js
await fetch(`${baseUrl}/${frameworkVersion}/resources/sap-ui-version.json`, { agent })
```
the file is downloaded.

BR,
Jacek

**Comment by petermuessig** [comment]
Good catch 🚀🚀 - therefore I originally added the `agent` code... :-) PR follows

**Comment by petermuessig** [comment]
Fix is about to be released...
