### ISSUE TITLE
[ui5-tooling-less-task] [ui5-tooling-less] not compiling the lees files with new update

### ISSUE THREAD

**Issue by AramSol** [ui5-community/ui5-ecosystem-showcase#896]
**Describe the bug**
I was using the ui5-tooling-less version "3.0.1," and everything was working perfectly. After the build process, all my Less files were compiled without any issues. However, I recently upgraded to version "3.0.2," and I found a problem. Now, the compiler stopped working, and I'm facing issues with the Less compilation.

I also attempted to use the ui5-tooling-less-task package, but I faced the same issue, and the problem persists.

code inside ui5.yaml builder task
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/39582300/c5c5d258-6447-45e0-ae8d-d5d163f29b48)

installed package
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/39582300/1f6c0387-abb0-43b4-9145-030a8f802a12)

dist folder after build
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/39582300/9a001965-572a-4bc2-9954-777f05d80364)

**Comment by petermuessig** [comment]
Thanks @AramSol for reporting. The issue will be fixed with ui5-tooling-less version 3.1.1
