### ISSUE TITLE
Corrupted image resource copied through includeAssets in ui5-tooling-module 

### ISSUE THREAD

**Issue by jump912** [ui5-community/ui5-ecosystem-showcase#902]
are are trying to use the NPM package leaflet in our UI5 app through the use of ui5-tooling-modules. the leaflet package relies on their CSS and marker images to plot the map. we configured the includeAssets like below. 

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/8d0fa36c-80f7-4ac9-8609-a00fa95ba6a4)

after running the build command below

```
ui5 build --config=ui5.yaml --clean-dest --dest dist
```

notice that the copied image resource is corrupted.

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/793f825f-c57e-4b3b-9919-7c9d34e72a88)

the same image resource is valid when viewed from the node_module directory

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/e8dbc541-5143-4ef7-bb3c-bb01fb6ba0b7)

**Comment by petermuessig** [comment]
Ah damn, good catch - binary files must be copied using the stream and not read as text. Fixing it with #904 - test and release pending...

**Comment by jump912** [comment]
Hi @petermuessig, that's amazing fast! We tested the new update, there's one scenario didn't work however.

It works with build and run UI5 server against the dist directory. The image resources copid to the thirdparty directory no longer corrupt.

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/c5c8251d-a221-417f-9fc2-2bbabd434463)

It didn't work without building. The image resources copied to the resources directory is still corrupted. The run command as below:

```
fiori run --config ./ui5-local.yaml
```

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/1579308/98bce5ac-b84f-4b4e-b57a-97cf738a6f44)

**Comment by petermuessig** [comment]
Yes, you are right - I just fixed the task and not the middleware. Here comes the fix for the middleware:
https://github.com/ui5-community/ui5-ecosystem-showcase/pull/907

I will release it directly when the PR is merged. Thanks for following up...

**Comment by petermuessig** [comment]
Issue is resolve with ui5-tooling-modules `3.2.4` which should be available in the next minutes

**Comment by jump912** [comment]
That worked! thanks, @petermuessig :)
