### ISSUE TITLE
[ui5-task-zipper] doesnt include sap-ui-custom.js and consorts when used in conjunction with generateStandaloneAppBundle

### ISSUE THREAD

**Issue by the-docta** [ui5-community/ui5-ecosystem-showcase#908]
**Is your feature request related to a problem? Please describe.**
When used in conjunction with the task `generateStandaloneAppBundle`, `ui5-task-zipper` doesn't include the generated files. Config parameter `additionalFiles` cant be used, as the generated files are yet in the buffer and not yet written to the file system at the time of zipping.

**Describe the solution you'd like**
I see two solutions:
* Always add the files `sap-ui-custom.js, sap-ui-custom-dbg.js, sap-ui-custom.js.map, sap-ui-custom-dbg.js.map` to ZIP, **_if_** they are being generated (would be "backwards compatible" in all cases, except when used in conjunction with 'generateStandaloneAppBundle`)
* Add new option: `includeStandaloneAppBundle`, which would enable or disable this behavior described in first bullet point (I wouldnt let it fail though, if `includeStandaloneAppBundle` is enabled, but `generateStandaloneAppBundle` is not (yet) executed

**Describe alternatives you've considered**
Config parameter `additionalFiles` cant be used, as the generated files are yet in the buffer and not yet written to the file system at the time of zipping.

**Additional context**
I would offer to implement the above proposed solution. Any comments?

**Comment by the-docta** [comment]
Implemented the first option (including test cases) and submitted as PR #909

**Comment by petermuessig** [comment]
Hi @the-docta ,

thanks for your suggestion - I'm more thinking in the direction to include any workspace resource as it only contains the resources from the `webapp` folder plus the created ones:

```js
	// get all application related resources
	let allResources;
	try {
		const wsResources = await workspace.byGlob(`**`);
		const depResources = await deps.byGlob(`**`);
		allResources = [...wsResources, ...depResources];
	} catch (e) {
		log.error(`Couldn't read resources: ${e}`);
	}
```

The prefix path calculated before:

```js
	// retrieve the resource path prefix (to get all application resources)
	const prefixPath = `/resources/${options.projectNamespace}/`;
```

is only relevant for removing the app namespace again as the resources are kept in the workspace list via the runtime resource path which will happen here:

```js
94: zip.addBuffer(buffer, resource.getPath().replace(prefixPath, "").replace(/^\//, "")); // Replace first forward slash at the start of the path
```

We could also think of only including the runtime resources of the dependencies and not the test-resources like today by making the glob for the `depResources` more fine granular:

```js
		const depResources = await deps.byGlob(`/resources/**`);
```

I would put this behind a configuration option to exclude test resources...

WDYT? From compatibility POV, I don't see an issue with adding the additionally created resources to the target ZIP. This should be the case, anyways...

 For the future, a nice option would be to be able to define `include` and `exclude` globs for the resources to be included - with that one can control on a fine granular level what he needs - but this is something I just thought of when seeing the big ZIP being created when running the self-contained build with the include all option. This packages the resources of all libs incl. their test-resources... Therefore, the idea to generically disable the packaging of the test-resources as suggested above... 

BIG thanks for contributing to the ecosystem! Highly appreciated... 😄

**Comment by petermuessig** [comment]
@the-docta I would leave out the `include`/`exclude` feature for now.

The include-all doesn't increase the workspace collection, only the dep collection, AFAIR. The workspace collection really only contains the resources of the `webapp` folder for applications plus the generated resources. So, this generic glob should be fine. Most probably doing the following should be sufficient:

```js
	// get all application related resources
	let allResources;
	try {
		const wsResources = await workspace.byGlob(`/resources/**`);
		const depResources = await deps.byGlob(`**`);
		allResources = [...wsResources, ...depResources];
	} catch (e) {
		log.error(`Couldn't read resources: ${e}`);
	}
```

This will include all runtime resources of the current project (incl. the generated ones) and all resources from the dependencies if the `includeAllDependencies` option is configured. 

Doing the above change + your tests should be sufficient IMO to make it work. I could release it once the PR is ready and tests are green...

THX again...

**Comment by the-docta** [comment]
right. just updated the PR as per your suggestion. local run pf `pnpm run test:ui5-task-zipper` is successful as well. Updated release number to 3.0.5 in the docs "Note"

**Comment by the-docta** [comment]
Thanks a lot! I think, this can be closed. 3.1.0 has been released to npm.org.

Sergei
