### ISSUE TITLE
[ui5-middleware-simpleproxy] Support for proxying single files has been stopped with version 3.1.3

### ISSUE THREAD

**Issue by VerenaRicharz** [ui5-community/ui5-ecosystem-showcase#924]
**Describe the bug**
With ui5-middleware-simpleproxy version 3.1.3 ([PR](https://github.com/ui5-community/ui5-ecosystem-showcase/pull/833)) the the support for proxying single files has been stopped. As it was just a patch version upgrade, I assume that the change was not introduced on purpose but came as a bug. Please, correct me if I am wrong.

**To Reproduce**
1. Clone the repository https://github.wdf.sap.corp/nextgenpayroll-matterhorn/net-formation-ui-components 
2. Run "npm install" und "npm run dev"
3. Execute the UnitTests by opening "http://localhost:3000/aspect/test/unit/unitTests.qunit.html" in the browser 
4. See the following error in the debugging tools console:
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/51702832/c25170e3-b0fb-4689-b40f-e514d85fa705)

**Expected behavior**
With ui5-middleware-simpleproxy version 3.1.2 the proxying of sinon.js (and all other potential 3rd party modules) did work without any issues and the QUnitTests could be executed. I would expect the same for version 3.1.3 onwards.

**Desktop**
 - Browser: Google Chrome 

**Additional context**
Our configuration for the ui5-middleware-simpleproxy is part of the [ui-cli](https://github.wdf.sap.corp/nextgenpayroll-zugspitze-infrastructure/ui-cli) tool which can be consumed as a dependency. For repositories of type "component" (as e.g. the net-formation-components-uis) the configuration looks [as follows](https://github.wdf.sap.corp/nextgenpayroll-zugspitze-infrastructure/ui-cli/blob/a62f856c178db7bece2b1bd98604fa552f43d08d/lib/util/ui5YamlBuilder.js#L485-L505).
Hence, in the case of the sinon.js dependency, we expect "/aspect/respurces/sinon.js" to be routed to "https://localhost:3000/resources/sinon.js".

We noticed, that the issue could be fixed by keeping the old logic and changing the following [codeline](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/854f333b0a8ea2d0ad4fe0b3814ca29dc27014ec/packages/ui5-middleware-simpleproxy/lib/proxy.js#L158) from:
`let pathname = baseUrl && url?.startsWith(baseUrl) ? url.substring(baseUrl.length - 1) : url;`
to
`let pathname = baseUrl && url?.startsWith(baseUrl) ? url.substring(baseUrl.length - 1) : ''; `
We weren't sure though of the background of this change. Was it on purpose that the url is now returned instead of an empty String or did it happen by accident? At least this change caused a stop in support of proxying single files for us.

Related Jira issue: https://jira.successfactors.com/browse/NGP-82687

**Comment by petermuessig** [comment]
Hi @VerenaRicharz ,

this is somehow a side-effect of the correct baseUrl handling. I also see that this project uses a special binary to run the UI5 tooling which preconfigures it and I need to investigate this first a bit more concrete. Somehow there is also some path concatenation happening which maybe relied on the old misbehavior of the proxy. As said, I need to dig a bit more how the things are playing together. 

BR, Peter

**Comment by VerenaRicharz** [comment]
Thanks, @petermuessig for delivering the bug fix so quickly!

**Comment by petermuessig** [comment]
Welcome, @VerenaRicharz
