### ISSUE TITLE
[ui5-tooling-modules] thirdparty library not loading in CAP Launchpad

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/ui5-ecosystem-showcase#941]
**Describe the bug**
similar to #915 i cant use the app in launchpad.html when loading the app in SAP CAP context

**To Reproduce**
1. `git clone https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter`
2. `git checkout chore/launchpad`
3. `pnpm i`
4. `pnpm start`
5. go to http://localhost:4004/launchpad.html#ordersv2fe-120
6. press button `Spreadsheet Upload`
7. `xlsx` was not loaded

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/13335743/11e34eec-d3a8-495f-a64a-cfc090d9a0e4)

**Expected behavior**
Load the xlsx like if the app is loaded via `pnpm start:v2fe:120` seperate and not via SAP CAP
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/13335743/7b4bef98-c35f-4163-8fdc-efa2882b0dab)

**Comment by petermuessig** [comment]
For me this works and the `xlsx` dependency is even packaged with the `Component-preload` of the spreadsheetimporter application. I cannot reproduce the issue - sorry... As said via Slack, maybe we have a call and debug your scenario...

**Comment by cgerold** [comment]
@marianfoo I have the same problem with xlsx and the Fiori Launchpad. Did you find a solution?
