### ISSUE TITLE
[cds-plugin-ui5] does not evaluate cds.env._home only process.pwd

### ISSUE THREAD

**Issue by nlaenger** [ui5-community/ui5-ecosystem-showcase#946]
**Describe the bug**
In case of running a wdi5 test, the current pwd is maybe not the cap folder.
In this case the plugin will search in the wrong path for the package.json

**To Reproduce**
1. Create a folder setup like:
- app
  - ui5_app1
    - test
  - ui5_app2
    - test
- cap (containing the backend)
- wdi5 (containing setup and config for wdi5)

**Expected behavior**
The plugin should take the path primary from cds.env._home 
=> I don't know if this is the right cds.env but ist seams to be correct on our cases (for example after init via: ```cds.test.in(__dirname + "/../cap");``` )

**Comment by petermuessig** [comment]
Fix is included in cds-plugin-ui5 version `0.8.1`
