### ISSUE TITLE
ui5-tooling-stringreplace: provide configurable separator to  "stringreplace<separator>" because default "." not working in ci/cd envs

### ISSUE THREAD

**Issue by PavelNikitsiuk** [ui5-community/ui5-ecosystem-showcase#948]
**Describtion.**
By default it's not possible to change `"."` separator in`"stringreplace."` and `"."` is not a valid character in shell / bash envs
hence it's not possible use stringreplace task/middleware in Continuous Integration & Delivery service of BTP

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/46888363/7e7d789a-4fd9-48ae-8b6c-9cd2671fc2fc)

**Proposal**
I've prepared changes that provide functionality to customize separator in this fork https://github.com/PavelNikitsiuk/ui5-ecosystem-showcase
 
**Additional context**
There was similar issue created before https://github.com/ui5-community/ui5-ecosystem-showcase/issues/339
and provided solution not cover this particular case with "stringreplace." placeholder

**Comment by petermuessig** [comment]
Your PR has been merged, release follows the next hours - need to check a few other things in the repo first...

**Comment by petermuessig** [comment]
Fix is included in ui5-tooling-stringreplace version `3.2.0`
