### ISSUE TITLE
[cds-plugin-ui5] Plugin also start when mocking a single service

### ISSUE THREAD

**Issue by nlaenger** [ui5-community/ui5-ecosystem-showcase#950]
**Describe the bug**
When using the mock function from cds:
https://cap.cloud.sap/docs/guides/using-services#mock-remote-service-as-odata-service-node-js

The cds-plugin-ui5 also loads.

I would have assumed that the mock function should only provide the "backend ODATA service".
I don't know if there is a "flag" or setting to ident that only the mocking is requested.

**To Reproduce**
1. start a "remote" service via "cds mock <servicename>"
2. beside the cds server also the ui5 plugin is startet

**Expected behavior**
When mocking a single service only "backend" function should be loaded

**Comment by petermuessig** [comment]
I found a solution:

```js
		// only for cds serve the cds-plugin-ui5 is active
		if (cds.cli?.command === "serve") {
```

When using cds serve or watch the cds.cli.command is serve - only then the plugin becomes active!

**Comment by petermuessig** [comment]
Fix is included in cds-plugin-ui5 version `0.8.1`

**Comment by nlaenger** [comment]
Hi @petermuessig,

I did check out this changes,
But now the plugin will not start at all in my wdi5 test (we start the server via ```cds.test(__dirname + "/../cap", "--in-memory", "--port", "4004");```.

Here are some example what the cds.env looks on the current change
```
// only for cds serve the cds-plugin-ui5 is active
		if (cds.cli?.command === "serve") {
```

cli: cds mock s4_payint
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/112619322/d1c2437b-8f56-42f3-ad2b-c7499daee4f9)

cli cds serve
![Screenshot 2024-02-19 070604](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/112619322/38a63f02-0455-43c9-af25-eab4bbf342af)

startet via: ```cds.test(__dirname + "/../cap", "--in-memory", "--port", "4004");```
![Screenshot 2024-02-19 070517](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/112619322/c4263f4d-0271-40fe-b482-9a68742cd7e3)


I guess:
* cds.options is a better place to get the info
* Also I don't know if ```process.env.CDS_PLUGIN_UI5_ACTIVE = "true"``` should beat the decision

regards
Norbert

**Comment by petermuessig** [comment]
Hi @nlaenger ,

I think we'll add a fallback strategy - if the `cds.cli.command` isn't defined, we check the `cds.options.service` for defining `all` - this should do the necessary trick for now...
