### ISSUE TITLE
[ui5-middleware-ui5] Not working with karma-ui5 for loading other applications (it does work only when loading libraries)

### ISSUE THREAD

**Issue by eurushibata** [ui5-community/ui5-ecosystem-showcase#960]
**Describe the bug**

We have extended cross.fnd.fiori.inbox and ui5-middleware-ui5 works fine when running **npm start** as bellow. (note: I've downloaded the standard fiori app to my local folder)

```
Server started
URL: http://localhost:8080
info server:custom-middleware:ui5-middleware-ui5 Mounting /resources/cross/fnd/fiori/inbox to UI5 app /Users/i319562/workspace/sol-ui-op/sap/ca_fiori_inbox (id=cross.fnd.fiori.inbox) using options={"mountPath":"/resources/cross/fnd/fiori/inbox"}
info graph:helpers:ui5Framework Using SAPUI5 version: 1.96.17
warn graph:helpers:ui5Framework Dependency sap.ca.scfld.md is deprecated and should not be used for new projects!
warn graph:helpers:ui5Framework Dependency sap.ca.scfld.md is restricted for use by SAP internal projects only! If the project cross.fnd.fiori.old.inbox is an SAP internal project, add the attribute "allowSapInternal: true" to its metadata configuration
warn graph:helpers:ui5Framework Dependency sap.ca.ui is deprecated and should not be used for new projects!
warn server:custom-middleware:ui5-middleware-serveframework 
```

However when running karma for unit test I don't see it getting mounted in the terminal and consequence is that the original fiori app isn't loaded:

```
cross.fnd.fiori.inbox.myinbox@2023.11.3 test:unit-ci
> karma start --ci --headless --unit

26 02 2024 12:16:16.640:INFO [karma-server]: Karma v6.4.3 server started at http://localhost:9876/
26 02 2024 12:16:16.642:INFO [launcher]: Launching browsers CustomChromeHeadless with concurrency unlimited
26 02 2024 12:16:16.645:INFO [launcher]: Starting browser ChromeHeadless
26 02 2024 12:16:17.069:INFO [Chrome Headless 122.0.6261.69 (Mac OS 10.15.7)]: Connected on socket k7k159Y8rsXHA8H_AAAB with id 18831157
[~~hook<ui5-middleware-ui5>~~] [ERROR] - Failed to hook into current server (most likely you are running a connect server which isn't supported by this hook)!
26 02 2024 12:16:17.637:WARN [web-server]: 404: /resources/cross/fnd/fiori/inbox/Component.js
26 02 2024 12:16:17.649:WARN [web-server]: 404: /resources/cross/fnd/fiori/inbox/Component.js
Chrome Headless 122.0.6261.69 (Mac OS 10.15.7) ERROR: '2024-02-26 12:16:17.649500 failed to load JavaScript resource: cross/fnd/fiori/old/inbox/Component.js -  sap.ui.ModuleSystem'
```

I have no problem when ui5-middleware-ui5 loads a library library.js, only when it loads an app Component.js.

**To Reproduce**
1. get any ui5 application that you want to "extend".
2. create the extended application.
3. try to run unit test for the newly created extended application.
4. karma-ui5 won't be able to get the modules configuration defined in your ui5-middleware-ui5 on ui5.yaml block.

**Only possible workaround**
The only workaround I found currently is by loading the content with serverstatic pointing to a rootPath
    - name: ui5-middleware-servestatic
      afterMiddleware: compression
      mountPath: /resources/cross/fnd/fiori/inbox
      configuration:
        rootPath: ../../../sap/ca_fiori_inbox/webapp/

**Comment by petermuessig** [comment]
Hi @eurushibata 

Karma is using `connect` and not `express` - therefore the hook which is needed to intercept the requests can't be installed there and the following error appears:

```
[~~hook<ui5-middleware-ui5>~~] [ERROR] - Failed to hook into current server (most likely you are running a connect server which isn't supported by this hook)!
```

This may need some additional investigation whether this is possible at all with Karma to use the `ui5-middleware-ui5`. Not sure yet and it requires some additional research...

**Comment by eurushibata** [comment]
Hi @petermuessig,
yes that is the odd part, sapui5-library works ok even having the error alert. but not sapui5-component.

**Comment by petermuessig** [comment]
Hi @eurushibata ,

would it be possible for you to provide me a sample application which I can use to reproduce the issue and to debug the tooling extension?

**Comment by petermuessig** [comment]
Hi @eurushibata 

I checked the coding of the [connect](https://github.com/senchalabs/connect/blob/master/index.js) implementation but unfortunately, there is no mechanism which allows to detect this and to get access to the `app` or `server` instance which is necessary for the hook function used by `ui5-middleware-ui5`, `ui5-middleware-approuter`, `ui5-middleware-cap`, `ui5-middleware-websocket` and `ui5-tooling-stringreplace-middleware`. All of those middlewares require to hook into the middlewares of the express server to do some rewriting. 

Unfortunately, I can't fix this issue here and for all servers using `connect` there is no support for these middlewares. This also includes Karma - as Karma is using also `connect`.

Sorry and best regards, Peter
