### ISSUE TITLE
[ui5-tooling-transpile-task] transpiled Javascript lacks renderer declaration

### ISSUE THREAD

**Issue by BenReim** [ui5-community/ui5-ecosystem-showcase#964]
When extending a UI5 Control where the render shall be inherited, a `renderer` member can be declared. 

However the renderer declaration is missing in the build result (transpiled JS file), which causes the UI5 runtime to incorrectly require the control renderer from the reuse library namespace. 

Reproducible sample: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/963

**Comment by petermuessig** [comment]
Hi Benjamin,

this issue goes down to the https://github.com/ui5-community/babel-plugin-transform-modules-ui5 project. It seems that it can't handle the `renderer` yet. I need to check if we can simply add this with small efforts.

BR,
Peter

**Comment by BenReim** [comment]
@petermuessig I realized that I made a mistake when declaring the renderer member, so it's actually not a bug in the plugin
