### ISSUE TITLE
[cds-plugin-ui5] Plugin is unable to load Formatter file

### ISSUE THREAD

**Issue by muellinho** [ui5-community/ui5-ecosystem-showcase#967]
Hi,

**Describe the bug**
In my UI5 App (Typescript) I created a Formatter.ts file, which I imported in my XMLView via the core:require mechanism:

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/23531536/6416fa11-563a-40d2-a6ff-ec78f7f72784)

When I run my CAP Server with the cds-plugin-ui5 to mount my UI5 App to the same server, my Formatter is to not loaded correctly:

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/23531536/6b80326a-84e1-4d99-ae13-3fbf486e5ee9)

**To Reproduce**
1. Run a UI5 app that defines a Formatter.ts file in the 'model' directory through a CAP server with the cds-plugin-ui5

**Expected behavior**
The Formatter gets loaded correctly.

When running the app via the UI5 Server directly, everything is fine and the Formatter is loaded correctly.

**Further information**
Additionally I've seen, that the loaded resources in general seem to be looking a little strange when running through the CAP server vs the UI5 Server (see below Screenshot)

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/23531536/76f79d70-3218-4382-a17a-fb971ed44269)

I also had the same behaviour once with a fragment inside the fragments directory, but this issue has solved itself automagically (maybe due to an update of the plugin?).

If you need further information, just ping me.

Thanks in advance
Best regards

**Comment by petermuessig** [comment]
Unfortunately, I can't reproduce the behavior - see #969 

Either the file doesn't exist or the `ui5-tooling-transpile-middleware` doesn't run for your application. To provide better support, access to your application code would be helpful. The `ui5.yaml` must include the `ui5-tooling-transpile-middleware` configuration and the file should exists with the similar case like when accessing it via URL. In the #969 this works - e.g. when running the cds sample via `pnpm dev-cds`. 

BTW: the difference in the file listing is OK, as on the left hand side, the `cds-plugin-ui5` overwrites the response and corrects the links so that the browser is usable. To see this the house icon is present on top left. So, this looks good when using the `cds-plugin-ui5` and it is running.

Please provide more details...

**Comment by muellinho** [comment]
Hi,

thanks for your response and sorry for the late reply...
I checked my config, the file exists and the `ui5-tooling-transpile-middleware` is running for my application.

In the meantime however I've figured out some new details / information:

In the time since opening this issue and now, I adjusted some minor bits in my app, including the ui5 bootstrap path to be absolute (`/resources/sap-ui-core.js`, instead of `resources/sap-ui-core.js`) since I needed it for my deployed scenario.

However when then testing locally again (after resetting the path to be relative), I noticed that the local server couldn't find the resources directory anymore. So I suspected some browser cache problem, but that wasn't the case.
After a little trial and error, with no success, I decided to _**reinstall my node_modules**_ and that did the trick.

This not only solved the problem with my Bootstrap not working, but also my original problem with my Formatter not being loaded.

Does the cds-plugin-ui5 or something else maybe cache my UI5 app in some package directory in the node_modules?

Best regards

**Comment by muellinho** [comment]
Addition:

I figured out what the problem in my project was.
I used the approach of using `cds-plugin-ui5` with a local file dependency to my UI5 app.

This causes a file-dependency in my node_modules which of course only gets updated when reinstalling...
Switching to the cds.env.folders.app config approach (since the app is in the same repo anyway) solved my problem, as there's no hard copy of the app in my node_modules.

**Comment by petermuessig** [comment]
@muellinho - thanks for the detailed analysis. The handling of dependencies of node is sometimes really weird. Maybe like the suggestion to restart the computer in case of issues is with node to remove node_modules and the package-lock and re-install the dependencies completely fresh... 😄
