### ISSUE TITLE
[ui5-tooling-stringreplace] .ts files not detected for replacing

### ISSUE THREAD

**Issue by KevinC0210** [ui5-community/ui5-ecosystem-showcase#979]
When using the ui5-tooling-stringreplace-task to replace values in files, TypeScript files always get ignored even when adding the .ts ending to the files configuration in the ui5.yaml. 
I looked into it and the issue is the MIME type of the ending .ts. In that case the MIME type results in video/mp2t. As video and image files are excluded from the stringreplace task, the TypeScript files are excluded as well.

When using the ui5-tooling-stringreplace the expected functionality is that it is also usable for replacing strings in TypeScript files.
The easiest fix for this issue would be to make an exception for .ts files when fetching the MIME type so that it does not use the MIME type video/mp2t which is provided by the mime type library.

**Comment by petermuessig** [comment]
I'll release a new version now - thanks for your finding and the PR! 🚀
