### ISSUE TITLE
ui5-tooling-transpile does not transpile sap.ui.core for the self-contained app

### ISSUE THREAD

**Issue by C3ntraX** [ui5-community/ui5-ecosystem-showcase#987]
**Describe the bug**
We have issues with the sap.ui.core to transpile down in production build with self-contained as target. Its not working because the file is somehow not considered.
In the UI5 version "1.120.9" they added a bunch of unsupported syntax for Chrome > 64. 

We actually need Chrome > 64 for some devices even for SAP Business One Webview.

Babel actually transpiled the syntax in my source code but the exact same syntax is not transpiled for the sap.ui.core inside the `sap-ui-custom.js`.

**To Reproduce**

**Expected behavior**
Transpiling only work when every javascript file is transpiled and not "some"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by C3ntraX** [comment]
This issue happens, if you try to transpile the whole app:

![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/44802503/31016407-ddef-48c4-8b43-05b22639a95b)

**Comment by petermuessig** [comment]
Hi @C3ntraX , the `ui5-tooling-transpile` hasn't been designed to transpile the whole bundle. It only transpiles the resources of the UI5 application or the custom UI5 library. I need to think about this requirement - this is also a bit more complicated as it would require to be injected into the build of the standard UI5 libraries such as the `sap.ui.core` library. But these libraries are built with their own task configuration. 

An option maybe would be to use standalone Babel after the build and to transform the `sap-ui-custom.js` but this maybe also not sufficient as all modulesloaded afterwards from the standard libraries of OpenUI5 or SAPUI5 will also not be transpiled. 

I'm wondering if we can get that running properly at all for your scenario... 

@codeworrior, @RandomByte, @matz3 - what's your opinion on that?

**Comment by C3ntraX** [comment]
Any news?

**Comment by matz3** [comment]
I'm sorry, but this does not sound like a scenario that we consider or foresee to support from our end. I also can't think of a good approach or workaround apart from post-processing all the files after the build. We currently do not plan to add custom tasks to the build process of framework libraries (or dependencies in general).

**Comment by petermuessig** [comment]
@C3ntraX - I think this can't be supported with the `ui5-tooling-transpile` middleware and task as it is related to the official UI5 libraries. A solution may be to do a post-processing of the `sap-ui-custom.js` with babel after the build took place. Sorry for not having better news... 😢
