### ISSUE TITLE
[ui5-tooling-modules] package pdfservices-node-sdk not resolveable

### ISSUE THREAD

**Issue by bsehp** [ui5-community/ui5-ecosystem-showcase#992]
**Describe the bug**
package https://www.npmjs.com/package/@adobe/pdfservices-node-sdk can not be used

**To Reproduce**
1. create empty ui5 app in bas
2. install npm modules ui5-tooling-modules & @adobe/pdfservices-node-sdk
3. add library to controller (sap.ui.define "@adobe/pdfservices-node-sdk" & function (Controller, ps)
4. change ui5.yaml according to https://www.npmjs.com/package/ui5-tooling-modules
6. ui5loader-dbg.js:1190 Uncaught (in promise) ModuleError: Failed to resolve dependencies of 'pdfservices/controller/View1.controller.js' 

**Expected behavior**
dependency can be resolved

**Screenshots**
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/69502388/8a6ba544-1551-480d-a53c-ca69c4bd3146)
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/69502388/6f4c89ca-389d-48d3-b412-4caff4a30326)
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/69502388/0e4b5fc4-1056-4214-a495-3c2c1c1e4cdb)
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/69502388/14c9eb55-d6b7-4544-8c3f-70c38703960b)
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/69502388/830bb7aa-20dc-40ac-9c7c-8582ad159bb3)

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome
 - Version 123.0.6312.123

**Comment by petermuessig** [comment]
@bsehp it looks like the `@adobe/pdfservices-node-sdk` requires file system operations which are not mocked consistently by the polyfills and therefore it lacks some functions which are needed in the loading flow of the module. I need to check whether we can do something here or not...

**Comment by swgtp** [comment]
Hey, I've got the same problem as well. I would appreciate it, if you find something.

**Comment by petermuessig** [comment]
@bsehp @swgtp - I just checked the documentation of the Adobe PDF Services API and it states the following:
https://developer.adobe.com/document-services/docs/overview/pdf-services-api/

> The SDK only supports server-based use cases where credentials are saved securely in a safe environment. SDK credentials should not be sent to untrusted environments or end user devices.

While looking into the issue during the generation, it lacks the existence of `fs` apis in the polyfills for the node modules. Although this could be manually tweaked, I wonder if this is really a proper scenario to have this library at client-side. IMO, you should use it on the server-side and send the requests to your server which communicates with the Adobe PDF Service. 

WDYT?

**Comment by petermuessig** [comment]
Closing due to my last answer - it's rather a server-side module.
